
version: '3'

tasks:
  build:
    desc: "Client: Build"
    cmds:
      - cargo fix --bin "solarance_beginnings" --allow-dirty
      - cargo build

  build-release:
    desc: "Client: Build Release"
    cmds:
      - cargo build --release
    
  run:
    desc: "Client: Run"
    cmds:
      - cargo run
    
  test-system:
    desc: "Client: Run Star System Test"
    cmds:
      - cargo run --example star_system_test

  generate:
    desc: "Client: Generate Bindings"
    cmds:
      - spacetime generate --lang rust --out-dir src/module_bindings --project-path ../server -y

  run-full:
    desc: "Generate bindings, build, and run client"
    deps:
      - generate
      - build
      - run

  stdsl-impls:
    desc: "Generate Impls for STDSL ID Types"
    cmds:
      - grep -rhIE -A1 '^pub struct (\w+Id) \{' . | sed -E --file=src/stdb/stdsl_sed_script.txt > src\stdb\stdsl_id_impls.txt
      # '^#\[table\(name = (\w+), public\)\]'
      # '^pub struct StationModuleId \{'  
      #    pub fn new\(id: u64\) -> Self \{
