# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

env:
  RUST_BACKTRACE: '1'

includes:
  server:
    taskfile: ./server/Taskfile.yml
    dir: server
  client: 
    taskfile: ./client/Taskfile.yml
    dir: client

tasks:

  # /// SpacetimeDB ///
  start-spacetime:
    desc: "STDB: Start SpacetimeDB"
    cmds:
      - spacetime start
    silent: false
    sources: []
    generates: []
    interactive: true

  show-login-token:
    desc: "STDB: Show Login Token"
    cmds:
      - spacetime login show --token

  list-local-dbs:
    desc: "STDB: List Local ST Databases"
    cmds:
      - spacetime list

  list-maincloud-dbs:
    desc: "STDB: List Maincloud ST Databases"
    cmds:
      - spacetime list -s maincloud

  view-logs:
    desc: "STDB: View Logs for Solarance"
    cmds:
      - spacetime logs solarance-beginnings
