version: "3"

tasks:
  build:
    desc: "Server: Build with ST"
    cmds:
      - cargo fix --lib -p solarance-spacetime-module --allow-dirty
      - spacetime build

  publish:
    desc: "Server: Publish to Local ST (Keeps DB)"
    cmds:
      - spacetime publish solarance-beginnings

  publish-clear:
    desc: "Server: Publish to Local ST & Clears DB"
    cmds:
      - spacetime publish -c solarance-beginnings -y

  publish-mc:
    desc: "Server: Publish to Maincloud ST (Keeps DB)"
    cmds:
      - spacetime publish -s maincloud solarance-beginnings -y

  publish-clear-mc:
    desc: "Server: Publish to Local ST & Clears DB"
    cmds:
      - spacetime publish -s maincloud -c solarance-beginnings -y

  delete-mc:
    desc: "Server: Delete Maincloud ST"
    cmds:
      - spacetime delete -s maincloud solarance-beginnings

  clear:
    desc: "Server: Clear ST Database"
    cmds:
      - spacetime publish solarance-beginnings --delete-data

  tables:
    desc: "Generate Table Names File for Easier Subscriptions"
    cmds:
      - grep -rhIE '^#\[table\(name = (\w+), public\)\]' . | sed -E 's/.*name = (\w+),.*/            "SELECT * FROM \1",/' > table_names.txt
      #            "SELECT * FROM global_chat_message",