//! Solarance:Beginnings — Galaxy Creator (privileged admin client).
//!
//! See `app.rs` for the UI and `stdb/connector.rs` for the SpacetimeDB
//! connection plumbing. The `server/bindings` module is generated by
//! `spacetime generate` (see `Taskfile.yml`).

pub mod app;
pub mod server;
pub mod stdb;
