// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::asteroid_sector_upkeep_timer_type::AsteroidSectorUpkeepTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AsteroidSectorUpkeepArgs {
    pub timer: AsteroidSectorUpkeepTimer,
}

impl From<AsteroidSectorUpkeepArgs> for super::Reducer {
    fn from(args: AsteroidSectorUpkeepArgs) -> Self {
        Self::AsteroidSectorUpkeep { timer: args.timer }
    }
}

impl __sdk::InModule for AsteroidSectorUpkeepArgs {
    type Module = super::RemoteModule;
}

pub struct AsteroidSectorUpkeepCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `asteroid_sector_upkeep`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait asteroid_sector_upkeep {
    /// Request that the remote module invoke the reducer `asteroid_sector_upkeep` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_asteroid_sector_upkeep`] callbacks.
    fn asteroid_sector_upkeep(&self, timer: AsteroidSectorUpkeepTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `asteroid_sector_upkeep`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AsteroidSectorUpkeepCallbackId`] can be passed to [`Self::remove_on_asteroid_sector_upkeep`]
    /// to cancel the callback.
    fn on_asteroid_sector_upkeep(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &AsteroidSectorUpkeepTimer) + Send + 'static,
    ) -> AsteroidSectorUpkeepCallbackId;
    /// Cancel a callback previously registered by [`Self::on_asteroid_sector_upkeep`],
    /// causing it not to run in the future.
    fn remove_on_asteroid_sector_upkeep(&self, callback: AsteroidSectorUpkeepCallbackId);
}

impl asteroid_sector_upkeep for super::RemoteReducers {
    fn asteroid_sector_upkeep(&self, timer: AsteroidSectorUpkeepTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("asteroid_sector_upkeep", AsteroidSectorUpkeepArgs { timer })
    }
    fn on_asteroid_sector_upkeep(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &AsteroidSectorUpkeepTimer)
            + Send
            + 'static,
    ) -> AsteroidSectorUpkeepCallbackId {
        AsteroidSectorUpkeepCallbackId(self.imp.on_reducer(
            "asteroid_sector_upkeep",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AsteroidSectorUpkeep { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_asteroid_sector_upkeep(&self, callback: AsteroidSectorUpkeepCallbackId) {
        self.imp
            .remove_on_reducer("asteroid_sector_upkeep", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `asteroid_sector_upkeep`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_asteroid_sector_upkeep {
    /// Set the call-reducer flags for the reducer `asteroid_sector_upkeep` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn asteroid_sector_upkeep(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_asteroid_sector_upkeep for super::SetReducerFlags {
    fn asteroid_sector_upkeep(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("asteroid_sector_upkeep", flags);
    }
}
