// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::asteroid_sector_type::AsteroidSector;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `asteroid_sector`.
///
/// Obtain a handle from the [`AsteroidSectorTableAccess::asteroid_sector`] method on [`super::RemoteTables`],
/// like `ctx.db.asteroid_sector()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asteroid_sector().on_insert(...)`.
pub struct AsteroidSectorTableHandle<'ctx> {
    imp: __sdk::TableHandle<AsteroidSector>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `asteroid_sector`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AsteroidSectorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AsteroidSectorTableHandle`], which mediates access to the table `asteroid_sector`.
    fn asteroid_sector(&self) -> AsteroidSectorTableHandle<'_>;
}

impl AsteroidSectorTableAccess for super::RemoteTables {
    fn asteroid_sector(&self) -> AsteroidSectorTableHandle<'_> {
        AsteroidSectorTableHandle {
            imp: self.imp.get_table::<AsteroidSector>("asteroid_sector"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AsteroidSectorInsertCallbackId(__sdk::CallbackId);
pub struct AsteroidSectorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AsteroidSectorTableHandle<'ctx> {
    type Row = AsteroidSector;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AsteroidSector> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AsteroidSectorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AsteroidSectorInsertCallbackId {
        AsteroidSectorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AsteroidSectorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AsteroidSectorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AsteroidSectorDeleteCallbackId {
        AsteroidSectorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AsteroidSectorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AsteroidSector>("asteroid_sector");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct AsteroidSectorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AsteroidSectorTableHandle<'ctx> {
    type UpdateCallbackId = AsteroidSectorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AsteroidSectorUpdateCallbackId {
        AsteroidSectorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AsteroidSectorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AsteroidSector>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AsteroidSector>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `asteroid_sector`,
/// which allows point queries on the field of the same name
/// via the [`AsteroidSectorIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asteroid_sector().id().find(...)`.
pub struct AsteroidSectorIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AsteroidSector, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AsteroidSectorTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `asteroid_sector`.
    pub fn id(&self) -> AsteroidSectorIdUnique<'ctx> {
        AsteroidSectorIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AsteroidSectorIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AsteroidSector> {
        self.imp.find(col_val)
    }
}
