// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AsteroidSector {
    pub id: u64,
    pub sparseness: u8,
    pub cluster_extent: f32,
    pub cluster_inner: Option<f32>,
}

impl __sdk::InModule for AsteroidSector {
    type Module = super::RemoteModule;
}
