// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::asteroid_type::Asteroid;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `asteroid`.
///
/// Obtain a handle from the [`AsteroidTableAccess::asteroid`] method on [`super::RemoteTables`],
/// like `ctx.db.asteroid()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asteroid().on_insert(...)`.
pub struct AsteroidTableHandle<'ctx> {
    imp: __sdk::TableHandle<Asteroid>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `asteroid`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AsteroidTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AsteroidTableHandle`], which mediates access to the table `asteroid`.
    fn asteroid(&self) -> AsteroidTableHandle<'_>;
}

impl AsteroidTableAccess for super::RemoteTables {
    fn asteroid(&self) -> AsteroidTableHandle<'_> {
        AsteroidTableHandle {
            imp: self.imp.get_table::<Asteroid>("asteroid"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AsteroidInsertCallbackId(__sdk::CallbackId);
pub struct AsteroidDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AsteroidTableHandle<'ctx> {
    type Row = Asteroid;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Asteroid> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AsteroidInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AsteroidInsertCallbackId {
        AsteroidInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AsteroidInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AsteroidDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AsteroidDeleteCallbackId {
        AsteroidDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AsteroidDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Asteroid>("asteroid");
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}
pub struct AsteroidUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AsteroidTableHandle<'ctx> {
    type UpdateCallbackId = AsteroidUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AsteroidUpdateCallbackId {
        AsteroidUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AsteroidUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Asteroid>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Asteroid>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `sobj_id` unique index on the table `asteroid`,
/// which allows point queries on the field of the same name
/// via the [`AsteroidSobjIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asteroid().sobj_id().find(...)`.
pub struct AsteroidSobjIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Asteroid, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AsteroidTableHandle<'ctx> {
    /// Get a handle on the `sobj_id` unique index on the table `asteroid`.
    pub fn sobj_id(&self) -> AsteroidSobjIdUnique<'ctx> {
        AsteroidSobjIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AsteroidSobjIdUnique<'ctx> {
    /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Asteroid> {
        self.imp.find(col_val)
    }
}
