// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cargo_crate_type::CargoCrate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cargo_crate`.
///
/// Obtain a handle from the [`CargoCrateTableAccess::cargo_crate`] method on [`super::RemoteTables`],
/// like `ctx.db.cargo_crate()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cargo_crate().on_insert(...)`.
pub struct CargoCrateTableHandle<'ctx> {
    imp: __sdk::TableHandle<CargoCrate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cargo_crate`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CargoCrateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CargoCrateTableHandle`], which mediates access to the table `cargo_crate`.
    fn cargo_crate(&self) -> CargoCrateTableHandle<'_>;
}

impl CargoCrateTableAccess for super::RemoteTables {
    fn cargo_crate(&self) -> CargoCrateTableHandle<'_> {
        CargoCrateTableHandle {
            imp: self.imp.get_table::<CargoCrate>("cargo_crate"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CargoCrateInsertCallbackId(__sdk::CallbackId);
pub struct CargoCrateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CargoCrateTableHandle<'ctx> {
    type Row = CargoCrate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CargoCrate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CargoCrateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CargoCrateInsertCallbackId {
        CargoCrateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CargoCrateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CargoCrateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CargoCrateDeleteCallbackId {
        CargoCrateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CargoCrateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CargoCrate>("cargo_crate");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}
pub struct CargoCrateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CargoCrateTableHandle<'ctx> {
    type UpdateCallbackId = CargoCrateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CargoCrateUpdateCallbackId {
        CargoCrateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CargoCrateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CargoCrate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CargoCrate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `cargo_crate`,
/// which allows point queries on the field of the same name
/// via the [`CargoCrateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cargo_crate().id().find(...)`.
pub struct CargoCrateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CargoCrate, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CargoCrateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `cargo_crate`.
    pub fn id(&self) -> CargoCrateIdUnique<'ctx> {
        CargoCrateIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CargoCrateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CargoCrate> {
        self.imp.find(col_val)
    }
}

/// Access to the `sobj_id` unique index on the table `cargo_crate`,
/// which allows point queries on the field of the same name
/// via the [`CargoCrateSobjIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cargo_crate().sobj_id().find(...)`.
pub struct CargoCrateSobjIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CargoCrate, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CargoCrateTableHandle<'ctx> {
    /// Get a handle on the `sobj_id` unique index on the table `cargo_crate`.
    pub fn sobj_id(&self) -> CargoCrateSobjIdUnique<'ctx> {
        CargoCrateSobjIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CargoCrateSobjIdUnique<'ctx> {
    /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CargoCrate> {
        self.imp.find(col_val)
    }
}
