// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CargoCrate {
    pub id: u64,
    pub current_sector_id: u64,
    pub sobj_id: u64,
    pub item_id: u32,
    pub quantity: u16,
    pub despawn_ts: Option<__sdk::Timestamp>,
    pub gfx_key: Option<String>,
}

impl __sdk::InModule for CargoCrate {
    type Module = super::RemoteModule;
}
