// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreatePlayerControlledShipArgs {
    pub identity: __sdk::Identity,
    pub username: String,
}

impl From<CreatePlayerControlledShipArgs> for super::Reducer {
    fn from(args: CreatePlayerControlledShipArgs) -> Self {
        Self::CreatePlayerControlledShip {
            identity: args.identity,
            username: args.username,
        }
    }
}

impl __sdk::InModule for CreatePlayerControlledShipArgs {
    type Module = super::RemoteModule;
}

pub struct CreatePlayerControlledShipCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_player_controlled_ship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_player_controlled_ship {
    /// Request that the remote module invoke the reducer `create_player_controlled_ship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_player_controlled_ship`] callbacks.
    fn create_player_controlled_ship(
        &self,
        identity: __sdk::Identity,
        username: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_player_controlled_ship`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreatePlayerControlledShipCallbackId`] can be passed to [`Self::remove_on_create_player_controlled_ship`]
    /// to cancel the callback.
    fn on_create_player_controlled_ship(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &String) + Send + 'static,
    ) -> CreatePlayerControlledShipCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_player_controlled_ship`],
    /// causing it not to run in the future.
    fn remove_on_create_player_controlled_ship(
        &self,
        callback: CreatePlayerControlledShipCallbackId,
    );
}

impl create_player_controlled_ship for super::RemoteReducers {
    fn create_player_controlled_ship(
        &self,
        identity: __sdk::Identity,
        username: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_player_controlled_ship",
            CreatePlayerControlledShipArgs { identity, username },
        )
    }
    fn on_create_player_controlled_ship(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &String)
            + Send
            + 'static,
    ) -> CreatePlayerControlledShipCallbackId {
        CreatePlayerControlledShipCallbackId(self.imp.on_reducer(
            "create_player_controlled_ship",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CreatePlayerControlledShip { identity, username },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, identity, username)
            }),
        ))
    }
    fn remove_on_create_player_controlled_ship(
        &self,
        callback: CreatePlayerControlledShipCallbackId,
    ) {
        self.imp
            .remove_on_reducer("create_player_controlled_ship", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_player_controlled_ship`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_player_controlled_ship {
    /// Set the call-reducer flags for the reducer `create_player_controlled_ship` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_player_controlled_ship(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_player_controlled_ship for super::SetReducerFlags {
    fn create_player_controlled_ship(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("create_player_controlled_ship", flags);
    }
}
