// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateSobjRandomArgs {
    pub sector_id: u64,
}

impl From<CreateSobjRandomArgs> for super::Reducer {
    fn from(args: CreateSobjRandomArgs) -> Self {
        Self::CreateSobjRandom {
            sector_id: args.sector_id,
        }
    }
}

impl __sdk::InModule for CreateSobjRandomArgs {
    type Module = super::RemoteModule;
}

pub struct CreateSobjRandomCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_sobj_random`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_sobj_random {
    /// Request that the remote module invoke the reducer `create_sobj_random` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_sobj_random`] callbacks.
    fn create_sobj_random(&self, sector_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_sobj_random`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateSobjRandomCallbackId`] can be passed to [`Self::remove_on_create_sobj_random`]
    /// to cancel the callback.
    fn on_create_sobj_random(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> CreateSobjRandomCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_sobj_random`],
    /// causing it not to run in the future.
    fn remove_on_create_sobj_random(&self, callback: CreateSobjRandomCallbackId);
}

impl create_sobj_random for super::RemoteReducers {
    fn create_sobj_random(&self, sector_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_sobj_random", CreateSobjRandomArgs { sector_id })
    }
    fn on_create_sobj_random(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> CreateSobjRandomCallbackId {
        CreateSobjRandomCallbackId(self.imp.on_reducer(
            "create_sobj_random",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateSobjRandom { sector_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, sector_id)
            }),
        ))
    }
    fn remove_on_create_sobj_random(&self, callback: CreateSobjRandomCallbackId) {
        self.imp.remove_on_reducer("create_sobj_random", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_sobj_random`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_sobj_random {
    /// Set the call-reducer flags for the reducer `create_sobj_random` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_sobj_random(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_sobj_random for super::SetReducerFlags {
    fn create_sobj_random(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_sobj_random", flags);
    }
}
