// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::stellar_object_id_type::StellarObjectId;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateTurnLeftControllerForArgs {
    pub sobj_id: StellarObjectId,
}

impl From<CreateTurnLeftControllerForArgs> for super::Reducer {
    fn from(args: CreateTurnLeftControllerForArgs) -> Self {
        Self::CreateTurnLeftControllerFor {
            sobj_id: args.sobj_id,
        }
    }
}

impl __sdk::InModule for CreateTurnLeftControllerForArgs {
    type Module = super::RemoteModule;
}

pub struct CreateTurnLeftControllerForCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_turn_left_controller_for`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_turn_left_controller_for {
    /// Request that the remote module invoke the reducer `create_turn_left_controller_for` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_turn_left_controller_for`] callbacks.
    fn create_turn_left_controller_for(&self, sobj_id: StellarObjectId) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_turn_left_controller_for`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateTurnLeftControllerForCallbackId`] can be passed to [`Self::remove_on_create_turn_left_controller_for`]
    /// to cancel the callback.
    fn on_create_turn_left_controller_for(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &StellarObjectId) + Send + 'static,
    ) -> CreateTurnLeftControllerForCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_turn_left_controller_for`],
    /// causing it not to run in the future.
    fn remove_on_create_turn_left_controller_for(
        &self,
        callback: CreateTurnLeftControllerForCallbackId,
    );
}

impl create_turn_left_controller_for for super::RemoteReducers {
    fn create_turn_left_controller_for(&self, sobj_id: StellarObjectId) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_turn_left_controller_for",
            CreateTurnLeftControllerForArgs { sobj_id },
        )
    }
    fn on_create_turn_left_controller_for(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &StellarObjectId) + Send + 'static,
    ) -> CreateTurnLeftControllerForCallbackId {
        CreateTurnLeftControllerForCallbackId(self.imp.on_reducer(
            "create_turn_left_controller_for",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateTurnLeftControllerFor { sobj_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, sobj_id)
            }),
        ))
    }
    fn remove_on_create_turn_left_controller_for(
        &self,
        callback: CreateTurnLeftControllerForCallbackId,
    ) {
        self.imp
            .remove_on_reducer("create_turn_left_controller_for", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_turn_left_controller_for`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_turn_left_controller_for {
    /// Set the call-reducer flags for the reducer `create_turn_left_controller_for` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_turn_left_controller_for(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_turn_left_controller_for for super::SetReducerFlags {
    fn create_turn_left_controller_for(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("create_turn_left_controller_for", flags);
    }
}
