// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum CurrentAction {
    Idle,

    Patrolling(Vec<Vec2>),

    MiningAsteroid(u64),

    AttackingTarget(u64),

    MovingToPosition(Vec2),

    JumpingWithGate(u64),

    JumpingWithHyperdrive(u64),

    Docking(u64),

    Undocking(u64),

    Fleeing(u64),

    Trading(u64),
}

impl __sdk::InModule for CurrentAction {
    type Module = super::RemoteModule;
}
