// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FactionChatMessage {
    pub id: u64,
    pub identity: __sdk::Identity,
    pub faction_id: u32,
    pub message: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for FactionChatMessage {
    type Module = super::RemoteModule;
}
