// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::faction_chat_message_type::FactionChatMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `faction_chat_message`.
///
/// Obtain a handle from the [`FactionChatMessageTableAccess::faction_chat_message`] method on [`super::RemoteTables`],
/// like `ctx.db.faction_chat_message()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.faction_chat_message().on_insert(...)`.
pub struct FactionChatMessageTableHandle<'ctx> {
    imp: __sdk::TableHandle<FactionChatMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `faction_chat_message`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FactionChatMessageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FactionChatMessageTableHandle`], which mediates access to the table `faction_chat_message`.
    fn faction_chat_message(&self) -> FactionChatMessageTableHandle<'_>;
}

impl FactionChatMessageTableAccess for super::RemoteTables {
    fn faction_chat_message(&self) -> FactionChatMessageTableHandle<'_> {
        FactionChatMessageTableHandle {
            imp: self
                .imp
                .get_table::<FactionChatMessage>("faction_chat_message"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FactionChatMessageInsertCallbackId(__sdk::CallbackId);
pub struct FactionChatMessageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FactionChatMessageTableHandle<'ctx> {
    type Row = FactionChatMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FactionChatMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FactionChatMessageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionChatMessageInsertCallbackId {
        FactionChatMessageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FactionChatMessageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FactionChatMessageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionChatMessageDeleteCallbackId {
        FactionChatMessageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FactionChatMessageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FactionChatMessage>("faction_chat_message");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct FactionChatMessageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FactionChatMessageTableHandle<'ctx> {
    type UpdateCallbackId = FactionChatMessageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FactionChatMessageUpdateCallbackId {
        FactionChatMessageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FactionChatMessageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<FactionChatMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FactionChatMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `faction_chat_message`,
/// which allows point queries on the field of the same name
/// via the [`FactionChatMessageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.faction_chat_message().id().find(...)`.
pub struct FactionChatMessageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FactionChatMessage, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FactionChatMessageTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `faction_chat_message`.
    pub fn id(&self) -> FactionChatMessageIdUnique<'ctx> {
        FactionChatMessageIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FactionChatMessageIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FactionChatMessage> {
        self.imp.find(col_val)
    }
}
