// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::faction_definition_type::FactionDefinition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `faction_definition`.
///
/// Obtain a handle from the [`FactionDefinitionTableAccess::faction_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.faction_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.faction_definition().on_insert(...)`.
pub struct FactionDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<FactionDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `faction_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FactionDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FactionDefinitionTableHandle`], which mediates access to the table `faction_definition`.
    fn faction_definition(&self) -> FactionDefinitionTableHandle<'_>;
}

impl FactionDefinitionTableAccess for super::RemoteTables {
    fn faction_definition(&self) -> FactionDefinitionTableHandle<'_> {
        FactionDefinitionTableHandle {
            imp: self
                .imp
                .get_table::<FactionDefinition>("faction_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FactionDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct FactionDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FactionDefinitionTableHandle<'ctx> {
    type Row = FactionDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FactionDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FactionDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionDefinitionInsertCallbackId {
        FactionDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FactionDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FactionDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionDefinitionDeleteCallbackId {
        FactionDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FactionDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FactionDefinition>("faction_definition");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct FactionDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FactionDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = FactionDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FactionDefinitionUpdateCallbackId {
        FactionDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FactionDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<FactionDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FactionDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `faction_definition`,
/// which allows point queries on the field of the same name
/// via the [`FactionDefinitionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.faction_definition().id().find(...)`.
pub struct FactionDefinitionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FactionDefinition, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FactionDefinitionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `faction_definition`.
    pub fn id(&self) -> FactionDefinitionIdUnique<'ctx> {
        FactionDefinitionIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FactionDefinitionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<FactionDefinition> {
        self.imp.find(col_val)
    }
}
