// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::global_chat_message_type::GlobalChatMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `global_chat_message`.
///
/// Obtain a handle from the [`GlobalChatMessageTableAccess::global_chat_message`] method on [`super::RemoteTables`],
/// like `ctx.db.global_chat_message()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_chat_message().on_insert(...)`.
pub struct GlobalChatMessageTableHandle<'ctx> {
    imp: __sdk::TableHandle<GlobalChatMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `global_chat_message`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GlobalChatMessageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GlobalChatMessageTableHandle`], which mediates access to the table `global_chat_message`.
    fn global_chat_message(&self) -> GlobalChatMessageTableHandle<'_>;
}

impl GlobalChatMessageTableAccess for super::RemoteTables {
    fn global_chat_message(&self) -> GlobalChatMessageTableHandle<'_> {
        GlobalChatMessageTableHandle {
            imp: self
                .imp
                .get_table::<GlobalChatMessage>("global_chat_message"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GlobalChatMessageInsertCallbackId(__sdk::CallbackId);
pub struct GlobalChatMessageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GlobalChatMessageTableHandle<'ctx> {
    type Row = GlobalChatMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GlobalChatMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GlobalChatMessageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalChatMessageInsertCallbackId {
        GlobalChatMessageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GlobalChatMessageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GlobalChatMessageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalChatMessageDeleteCallbackId {
        GlobalChatMessageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GlobalChatMessageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GlobalChatMessage>("global_chat_message");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct GlobalChatMessageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GlobalChatMessageTableHandle<'ctx> {
    type UpdateCallbackId = GlobalChatMessageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GlobalChatMessageUpdateCallbackId {
        GlobalChatMessageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GlobalChatMessageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GlobalChatMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GlobalChatMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `global_chat_message`,
/// which allows point queries on the field of the same name
/// via the [`GlobalChatMessageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_chat_message().id().find(...)`.
pub struct GlobalChatMessageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GlobalChatMessage, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GlobalChatMessageTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `global_chat_message`.
    pub fn id(&self) -> GlobalChatMessageIdUnique<'ctx> {
        GlobalChatMessageIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GlobalChatMessageIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GlobalChatMessage> {
        self.imp.find(col_val)
    }
}
