// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::global_config_type::GlobalConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `global_config`.
///
/// Obtain a handle from the [`GlobalConfigTableAccess::global_config`] method on [`super::RemoteTables`],
/// like `ctx.db.global_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_config().on_insert(...)`.
pub struct GlobalConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<GlobalConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `global_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GlobalConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GlobalConfigTableHandle`], which mediates access to the table `global_config`.
    fn global_config(&self) -> GlobalConfigTableHandle<'_>;
}

impl GlobalConfigTableAccess for super::RemoteTables {
    fn global_config(&self) -> GlobalConfigTableHandle<'_> {
        GlobalConfigTableHandle {
            imp: self.imp.get_table::<GlobalConfig>("global_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GlobalConfigInsertCallbackId(__sdk::CallbackId);
pub struct GlobalConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GlobalConfigTableHandle<'ctx> {
    type Row = GlobalConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GlobalConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GlobalConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalConfigInsertCallbackId {
        GlobalConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GlobalConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GlobalConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalConfigDeleteCallbackId {
        GlobalConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GlobalConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GlobalConfig>("global_config");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct GlobalConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GlobalConfigTableHandle<'ctx> {
    type UpdateCallbackId = GlobalConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GlobalConfigUpdateCallbackId {
        GlobalConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GlobalConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GlobalConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GlobalConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `global_config`,
/// which allows point queries on the field of the same name
/// via the [`GlobalConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_config().id().find(...)`.
pub struct GlobalConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GlobalConfig, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GlobalConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `global_config`.
    pub fn id(&self) -> GlobalConfigIdUnique<'ctx> {
        GlobalConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GlobalConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GlobalConfig> {
        self.imp.find(col_val)
    }
}
