// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GrantPrivilageToClientArgs {
    pub identity: __sdk::Identity,
    pub description: String,
    pub privilage: u32,
}

impl From<GrantPrivilageToClientArgs> for super::Reducer {
    fn from(args: GrantPrivilageToClientArgs) -> Self {
        Self::GrantPrivilageToClient {
            identity: args.identity,
            description: args.description,
            privilage: args.privilage,
        }
    }
}

impl __sdk::InModule for GrantPrivilageToClientArgs {
    type Module = super::RemoteModule;
}

pub struct GrantPrivilageToClientCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `grant_privilage_to_client`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait grant_privilage_to_client {
    /// Request that the remote module invoke the reducer `grant_privilage_to_client` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_grant_privilage_to_client`] callbacks.
    fn grant_privilage_to_client(
        &self,
        identity: __sdk::Identity,
        description: String,
        privilage: u32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `grant_privilage_to_client`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GrantPrivilageToClientCallbackId`] can be passed to [`Self::remove_on_grant_privilage_to_client`]
    /// to cancel the callback.
    fn on_grant_privilage_to_client(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &String, &u32)
            + Send
            + 'static,
    ) -> GrantPrivilageToClientCallbackId;
    /// Cancel a callback previously registered by [`Self::on_grant_privilage_to_client`],
    /// causing it not to run in the future.
    fn remove_on_grant_privilage_to_client(&self, callback: GrantPrivilageToClientCallbackId);
}

impl grant_privilage_to_client for super::RemoteReducers {
    fn grant_privilage_to_client(
        &self,
        identity: __sdk::Identity,
        description: String,
        privilage: u32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "grant_privilage_to_client",
            GrantPrivilageToClientArgs {
                identity,
                description,
                privilage,
            },
        )
    }
    fn on_grant_privilage_to_client(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &String, &u32)
            + Send
            + 'static,
    ) -> GrantPrivilageToClientCallbackId {
        GrantPrivilageToClientCallbackId(self.imp.on_reducer(
            "grant_privilage_to_client",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::GrantPrivilageToClient {
                                    identity,
                                    description,
                                    privilage,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, identity, description, privilage)
            }),
        ))
    }
    fn remove_on_grant_privilage_to_client(&self, callback: GrantPrivilageToClientCallbackId) {
        self.imp
            .remove_on_reducer("grant_privilage_to_client", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `grant_privilage_to_client`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_grant_privilage_to_client {
    /// Set the call-reducer flags for the reducer `grant_privilage_to_client` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn grant_privilage_to_client(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_grant_privilage_to_client for super::SetReducerFlags {
    fn grant_privilage_to_client(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("grant_privilage_to_client", flags);
    }
}
