// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_category_type::ItemCategory;
use super::item_metadata_type::ItemMetadata;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ItemDefinition {
    pub id: u32,
    pub name: String,
    pub description: Option<String>,
    pub category: ItemCategory,
    pub base_value: u32,
    pub volume_per_unit: u16,
    pub units_per_stack: u8,
    pub metadata: Vec<ItemMetadata>,
    pub gfx_key: Option<String>,
}

impl __sdk::InModule for ItemDefinition {
    type Module = super::RemoteModule;
}
