// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_category_type::ItemCategory;
use super::item_definition_type::ItemDefinition;
use super::item_metadata_type::ItemMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `item_definition`.
///
/// Obtain a handle from the [`ItemDefinitionTableAccess::item_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.item_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_definition().on_insert(...)`.
pub struct ItemDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `item_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ItemDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ItemDefinitionTableHandle`], which mediates access to the table `item_definition`.
    fn item_definition(&self) -> ItemDefinitionTableHandle<'_>;
}

impl ItemDefinitionTableAccess for super::RemoteTables {
    fn item_definition(&self) -> ItemDefinitionTableHandle<'_> {
        ItemDefinitionTableHandle {
            imp: self.imp.get_table::<ItemDefinition>("item_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ItemDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct ItemDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ItemDefinitionTableHandle<'ctx> {
    type Row = ItemDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ItemDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDefinitionInsertCallbackId {
        ItemDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ItemDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDefinitionDeleteCallbackId {
        ItemDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemDefinition>("item_definition");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct ItemDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ItemDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = ItemDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemDefinitionUpdateCallbackId {
        ItemDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ItemDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ItemDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `item_definition`,
/// which allows point queries on the field of the same name
/// via the [`ItemDefinitionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_definition().id().find(...)`.
pub struct ItemDefinitionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ItemDefinition, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ItemDefinitionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `item_definition`.
    pub fn id(&self) -> ItemDefinitionIdUnique<'ctx> {
        ItemDefinitionIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ItemDefinitionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ItemDefinition> {
        self.imp.find(col_val)
    }
}
