// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum ItemMetadata {
    DamageBoost(f32),

    ShieldBoost(f32),

    CargoCapacityBoost(u16),

    MiningSpeedMultiplier(f32),

    EnergyConsumption(f32),

    SpecialEffect(String),

    Stacks(u8),

    NoStacking,

    NoTrade,

    NoSell,

    NoDrop,
}

impl __sdk::InModule for ItemMetadata {
    type Module = super::RemoteModule;
}
