// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct JumpGate {
    pub sobj_id: u64,
    pub current_sector_id: u64,
    pub target_sector_id: u64,
    pub target_gate_arrival_pos: Vec2,
    pub gfx_key: Option<String>,
    pub is_active: bool,
}

impl __sdk::InModule for JumpGate {
    type Module = super::RemoteModule;
}
