// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::jump_gate_type::JumpGate;
use super::vec_2_type::Vec2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `jump_gate`.
///
/// Obtain a handle from the [`JumpGateTableAccess::jump_gate`] method on [`super::RemoteTables`],
/// like `ctx.db.jump_gate()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.jump_gate().on_insert(...)`.
pub struct JumpGateTableHandle<'ctx> {
    imp: __sdk::TableHandle<JumpGate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `jump_gate`.
///
/// Implemented for [`super::RemoteTables`].
pub trait JumpGateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`JumpGateTableHandle`], which mediates access to the table `jump_gate`.
    fn jump_gate(&self) -> JumpGateTableHandle<'_>;
}

impl JumpGateTableAccess for super::RemoteTables {
    fn jump_gate(&self) -> JumpGateTableHandle<'_> {
        JumpGateTableHandle {
            imp: self.imp.get_table::<JumpGate>("jump_gate"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct JumpGateInsertCallbackId(__sdk::CallbackId);
pub struct JumpGateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for JumpGateTableHandle<'ctx> {
    type Row = JumpGate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = JumpGate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = JumpGateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> JumpGateInsertCallbackId {
        JumpGateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: JumpGateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = JumpGateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> JumpGateDeleteCallbackId {
        JumpGateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: JumpGateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<JumpGate>("jump_gate");
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}
pub struct JumpGateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for JumpGateTableHandle<'ctx> {
    type UpdateCallbackId = JumpGateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> JumpGateUpdateCallbackId {
        JumpGateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: JumpGateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<JumpGate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<JumpGate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `sobj_id` unique index on the table `jump_gate`,
/// which allows point queries on the field of the same name
/// via the [`JumpGateSobjIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.jump_gate().sobj_id().find(...)`.
pub struct JumpGateSobjIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<JumpGate, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> JumpGateTableHandle<'ctx> {
    /// Get a handle on the `sobj_id` unique index on the table `jump_gate`.
    pub fn sobj_id(&self) -> JumpGateSobjIdUnique<'ctx> {
        JumpGateSobjIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> JumpGateSobjIdUnique<'ctx> {
    /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<JumpGate> {
        self.imp.find(col_val)
    }
}
