// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveStellarObjectsArgs {}

impl From<MoveStellarObjectsArgs> for super::Reducer {
    fn from(args: MoveStellarObjectsArgs) -> Self {
        Self::MoveStellarObjects
    }
}

impl __sdk::InModule for MoveStellarObjectsArgs {
    type Module = super::RemoteModule;
}

pub struct MoveStellarObjectsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_stellar_objects`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_stellar_objects {
    /// Request that the remote module invoke the reducer `move_stellar_objects` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_move_stellar_objects`] callbacks.
    fn move_stellar_objects(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `move_stellar_objects`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MoveStellarObjectsCallbackId`] can be passed to [`Self::remove_on_move_stellar_objects`]
    /// to cancel the callback.
    fn on_move_stellar_objects(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> MoveStellarObjectsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_move_stellar_objects`],
    /// causing it not to run in the future.
    fn remove_on_move_stellar_objects(&self, callback: MoveStellarObjectsCallbackId);
}

impl move_stellar_objects for super::RemoteReducers {
    fn move_stellar_objects(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("move_stellar_objects", MoveStellarObjectsArgs {})
    }
    fn on_move_stellar_objects(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> MoveStellarObjectsCallbackId {
        MoveStellarObjectsCallbackId(self.imp.on_reducer(
            "move_stellar_objects",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MoveStellarObjects {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_move_stellar_objects(&self, callback: MoveStellarObjectsCallbackId) {
        self.imp
            .remove_on_reducer("move_stellar_objects", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `move_stellar_objects`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_move_stellar_objects {
    /// Set the call-reducer flags for the reducer `move_stellar_objects` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn move_stellar_objects(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_move_stellar_objects for super::SetReducerFlags {
    fn move_stellar_objects(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("move_stellar_objects", flags);
    }
}
