// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_controller_timer_type::PlayerControllerTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerControllerUpkeepArgs {
    pub timer: PlayerControllerTimer,
}

impl From<PlayerControllerUpkeepArgs> for super::Reducer {
    fn from(args: PlayerControllerUpkeepArgs) -> Self {
        Self::PlayerControllerUpkeep { timer: args.timer }
    }
}

impl __sdk::InModule for PlayerControllerUpkeepArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerControllerUpkeepCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_controller_upkeep`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_controller_upkeep {
    /// Request that the remote module invoke the reducer `player_controller_upkeep` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_controller_upkeep`] callbacks.
    fn player_controller_upkeep(&self, timer: PlayerControllerTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_controller_upkeep`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerControllerUpkeepCallbackId`] can be passed to [`Self::remove_on_player_controller_upkeep`]
    /// to cancel the callback.
    fn on_player_controller_upkeep(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerControllerTimer) + Send + 'static,
    ) -> PlayerControllerUpkeepCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_controller_upkeep`],
    /// causing it not to run in the future.
    fn remove_on_player_controller_upkeep(&self, callback: PlayerControllerUpkeepCallbackId);
}

impl player_controller_upkeep for super::RemoteReducers {
    fn player_controller_upkeep(&self, timer: PlayerControllerTimer) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "player_controller_upkeep",
            PlayerControllerUpkeepArgs { timer },
        )
    }
    fn on_player_controller_upkeep(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerControllerTimer) + Send + 'static,
    ) -> PlayerControllerUpkeepCallbackId {
        PlayerControllerUpkeepCallbackId(self.imp.on_reducer(
            "player_controller_upkeep",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerControllerUpkeep { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_player_controller_upkeep(&self, callback: PlayerControllerUpkeepCallbackId) {
        self.imp
            .remove_on_reducer("player_controller_upkeep", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_controller_upkeep`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_controller_upkeep {
    /// Set the call-reducer flags for the reducer `player_controller_upkeep` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_controller_upkeep(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_controller_upkeep for super::SetReducerFlags {
    fn player_controller_upkeep(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("player_controller_upkeep", flags);
    }
}
