// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::current_action_type::CurrentAction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerController {
    pub identity: __sdk::Identity,
    pub stellar_object_id: Option<u64>,
    pub up: bool,
    pub down: bool,
    pub left: bool,
    pub right: bool,
    pub current_action: CurrentAction,
    pub activate_jump_drive: bool,
    pub tractor_beam_on: bool,
    pub mining_laser_on: bool,
    pub cargo_bay_open: bool,
    pub dock: bool,
    pub undock: bool,
    pub shield_boost: bool,
    pub fire_weapons: bool,
    pub fire_missle: bool,
    pub targetted_sobj_id: Option<u64>,
}

impl __sdk::InModule for PlayerController {
    type Module = super::RemoteModule;
}
