// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_controller_timer_type::PlayerControllerTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_controller_timer`.
///
/// Obtain a handle from the [`PlayerControllerTimerTableAccess::player_controller_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.player_controller_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_controller_timer().on_insert(...)`.
pub struct PlayerControllerTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerControllerTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_controller_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerControllerTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerControllerTimerTableHandle`], which mediates access to the table `player_controller_timer`.
    fn player_controller_timer(&self) -> PlayerControllerTimerTableHandle<'_>;
}

impl PlayerControllerTimerTableAccess for super::RemoteTables {
    fn player_controller_timer(&self) -> PlayerControllerTimerTableHandle<'_> {
        PlayerControllerTimerTableHandle {
            imp: self
                .imp
                .get_table::<PlayerControllerTimer>("player_controller_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerControllerTimerInsertCallbackId(__sdk::CallbackId);
pub struct PlayerControllerTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerControllerTimerTableHandle<'ctx> {
    type Row = PlayerControllerTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerControllerTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerControllerTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerControllerTimerInsertCallbackId {
        PlayerControllerTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerControllerTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerControllerTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerControllerTimerDeleteCallbackId {
        PlayerControllerTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerControllerTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerControllerTimer>("player_controller_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct PlayerControllerTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerControllerTimerTableHandle<'ctx> {
    type UpdateCallbackId = PlayerControllerTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerControllerTimerUpdateCallbackId {
        PlayerControllerTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerControllerTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerControllerTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerControllerTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `player_controller_timer`,
/// which allows point queries on the field of the same name
/// via the [`PlayerControllerTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_controller_timer().scheduled_id().find(...)`.
pub struct PlayerControllerTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerControllerTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerControllerTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `player_controller_timer`.
    pub fn scheduled_id(&self) -> PlayerControllerTimerScheduledIdUnique<'ctx> {
        PlayerControllerTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerControllerTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerControllerTimer> {
        self.imp.find(col_val)
    }
}
