// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::current_action_type::CurrentAction;
use super::player_controller_type::PlayerController;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_controller`.
///
/// Obtain a handle from the [`PlayerControllerTableAccess::player_controller`] method on [`super::RemoteTables`],
/// like `ctx.db.player_controller()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_controller().on_insert(...)`.
pub struct PlayerControllerTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerController>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_controller`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerControllerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerControllerTableHandle`], which mediates access to the table `player_controller`.
    fn player_controller(&self) -> PlayerControllerTableHandle<'_>;
}

impl PlayerControllerTableAccess for super::RemoteTables {
    fn player_controller(&self) -> PlayerControllerTableHandle<'_> {
        PlayerControllerTableHandle {
            imp: self.imp.get_table::<PlayerController>("player_controller"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerControllerInsertCallbackId(__sdk::CallbackId);
pub struct PlayerControllerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerControllerTableHandle<'ctx> {
    type Row = PlayerController;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerController> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerControllerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerControllerInsertCallbackId {
        PlayerControllerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerControllerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerControllerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerControllerDeleteCallbackId {
        PlayerControllerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerControllerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerController>("player_controller");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct PlayerControllerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerControllerTableHandle<'ctx> {
    type UpdateCallbackId = PlayerControllerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerControllerUpdateCallbackId {
        PlayerControllerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerControllerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerController>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerController>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `player_controller`,
/// which allows point queries on the field of the same name
/// via the [`PlayerControllerIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_controller().identity().find(...)`.
pub struct PlayerControllerIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerController, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerControllerTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `player_controller`.
    pub fn identity(&self) -> PlayerControllerIdentityUnique<'ctx> {
        PlayerControllerIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerControllerIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerController> {
        self.imp.find(col_val)
    }
}
