// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::privileged_client_type::PrivilegedClient;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `privileged_client`.
///
/// Obtain a handle from the [`PrivilegedClientTableAccess::privileged_client`] method on [`super::RemoteTables`],
/// like `ctx.db.privileged_client()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.privileged_client().on_insert(...)`.
pub struct PrivilegedClientTableHandle<'ctx> {
    imp: __sdk::TableHandle<PrivilegedClient>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `privileged_client`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PrivilegedClientTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PrivilegedClientTableHandle`], which mediates access to the table `privileged_client`.
    fn privileged_client(&self) -> PrivilegedClientTableHandle<'_>;
}

impl PrivilegedClientTableAccess for super::RemoteTables {
    fn privileged_client(&self) -> PrivilegedClientTableHandle<'_> {
        PrivilegedClientTableHandle {
            imp: self.imp.get_table::<PrivilegedClient>("privileged_client"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PrivilegedClientInsertCallbackId(__sdk::CallbackId);
pub struct PrivilegedClientDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PrivilegedClientTableHandle<'ctx> {
    type Row = PrivilegedClient;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PrivilegedClient> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PrivilegedClientInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PrivilegedClientInsertCallbackId {
        PrivilegedClientInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PrivilegedClientInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PrivilegedClientDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PrivilegedClientDeleteCallbackId {
        PrivilegedClientDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PrivilegedClientDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PrivilegedClient>("privileged_client");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct PrivilegedClientUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PrivilegedClientTableHandle<'ctx> {
    type UpdateCallbackId = PrivilegedClientUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PrivilegedClientUpdateCallbackId {
        PrivilegedClientUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PrivilegedClientUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PrivilegedClient>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PrivilegedClient>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `privileged_client`,
/// which allows point queries on the field of the same name
/// via the [`PrivilegedClientIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.privileged_client().identity().find(...)`.
pub struct PrivilegedClientIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PrivilegedClient, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PrivilegedClientTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `privileged_client`.
    pub fn identity(&self) -> PrivilegedClientIdentityUnique<'ctx> {
        PrivilegedClientIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PrivilegedClientIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PrivilegedClient> {
        self.imp.find(col_val)
    }
}
