// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::transforms_timer_type::TransformsTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecalculateSobjTransformsArgs {
    pub timer: TransformsTimer,
}

impl From<RecalculateSobjTransformsArgs> for super::Reducer {
    fn from(args: RecalculateSobjTransformsArgs) -> Self {
        Self::RecalculateSobjTransforms { timer: args.timer }
    }
}

impl __sdk::InModule for RecalculateSobjTransformsArgs {
    type Module = super::RemoteModule;
}

pub struct RecalculateSobjTransformsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `recalculate_sobj_transforms`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait recalculate_sobj_transforms {
    /// Request that the remote module invoke the reducer `recalculate_sobj_transforms` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_recalculate_sobj_transforms`] callbacks.
    fn recalculate_sobj_transforms(&self, timer: TransformsTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `recalculate_sobj_transforms`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RecalculateSobjTransformsCallbackId`] can be passed to [`Self::remove_on_recalculate_sobj_transforms`]
    /// to cancel the callback.
    fn on_recalculate_sobj_transforms(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &TransformsTimer) + Send + 'static,
    ) -> RecalculateSobjTransformsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_recalculate_sobj_transforms`],
    /// causing it not to run in the future.
    fn remove_on_recalculate_sobj_transforms(&self, callback: RecalculateSobjTransformsCallbackId);
}

impl recalculate_sobj_transforms for super::RemoteReducers {
    fn recalculate_sobj_transforms(&self, timer: TransformsTimer) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "recalculate_sobj_transforms",
            RecalculateSobjTransformsArgs { timer },
        )
    }
    fn on_recalculate_sobj_transforms(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &TransformsTimer) + Send + 'static,
    ) -> RecalculateSobjTransformsCallbackId {
        RecalculateSobjTransformsCallbackId(self.imp.on_reducer(
            "recalculate_sobj_transforms",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RecalculateSobjTransforms { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_recalculate_sobj_transforms(&self, callback: RecalculateSobjTransformsCallbackId) {
        self.imp
            .remove_on_reducer("recalculate_sobj_transforms", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `recalculate_sobj_transforms`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_recalculate_sobj_transforms {
    /// Set the call-reducer flags for the reducer `recalculate_sobj_transforms` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn recalculate_sobj_transforms(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_recalculate_sobj_transforms for super::SetReducerFlags {
    fn recalculate_sobj_transforms(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("recalculate_sobj_transforms", flags);
    }
}
