// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_windows_timer_type::PlayerWindowsTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecalculatePlayerWindowsArgs {
    pub timer: PlayerWindowsTimer,
}

impl From<RecalculatePlayerWindowsArgs> for super::Reducer {
    fn from(args: RecalculatePlayerWindowsArgs) -> Self {
        Self::RecalculatePlayerWindows { timer: args.timer }
    }
}

impl __sdk::InModule for RecalculatePlayerWindowsArgs {
    type Module = super::RemoteModule;
}

pub struct RecalculatePlayerWindowsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `recalculate_player_windows`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait recalculate_player_windows {
    /// Request that the remote module invoke the reducer `recalculate_player_windows` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_recalculate_player_windows`] callbacks.
    fn recalculate_player_windows(&self, timer: PlayerWindowsTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `recalculate_player_windows`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RecalculatePlayerWindowsCallbackId`] can be passed to [`Self::remove_on_recalculate_player_windows`]
    /// to cancel the callback.
    fn on_recalculate_player_windows(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerWindowsTimer) + Send + 'static,
    ) -> RecalculatePlayerWindowsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_recalculate_player_windows`],
    /// causing it not to run in the future.
    fn remove_on_recalculate_player_windows(&self, callback: RecalculatePlayerWindowsCallbackId);
}

impl recalculate_player_windows for super::RemoteReducers {
    fn recalculate_player_windows(&self, timer: PlayerWindowsTimer) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "recalculate_player_windows",
            RecalculatePlayerWindowsArgs { timer },
        )
    }
    fn on_recalculate_player_windows(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerWindowsTimer) + Send + 'static,
    ) -> RecalculatePlayerWindowsCallbackId {
        RecalculatePlayerWindowsCallbackId(self.imp.on_reducer(
            "recalculate_player_windows",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RecalculatePlayerWindows { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_recalculate_player_windows(&self, callback: RecalculatePlayerWindowsCallbackId) {
        self.imp
            .remove_on_reducer("recalculate_player_windows", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `recalculate_player_windows`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_recalculate_player_windows {
    /// Set the call-reducer flags for the reducer `recalculate_player_windows` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn recalculate_player_windows(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_recalculate_player_windows for super::SetReducerFlags {
    fn recalculate_player_windows(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("recalculate_player_windows", flags);
    }
}
