// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::privileged_client_identity_type::PrivilegedClientIdentity;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RevokePrivilageFromClientArgs {
    pub client_identity: PrivilegedClientIdentity,
}

impl From<RevokePrivilageFromClientArgs> for super::Reducer {
    fn from(args: RevokePrivilageFromClientArgs) -> Self {
        Self::RevokePrivilageFromClient {
            client_identity: args.client_identity,
        }
    }
}

impl __sdk::InModule for RevokePrivilageFromClientArgs {
    type Module = super::RemoteModule;
}

pub struct RevokePrivilageFromClientCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `revoke_privilage_from_client`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait revoke_privilage_from_client {
    /// Request that the remote module invoke the reducer `revoke_privilage_from_client` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_revoke_privilage_from_client`] callbacks.
    fn revoke_privilage_from_client(
        &self,
        client_identity: PrivilegedClientIdentity,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `revoke_privilage_from_client`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RevokePrivilageFromClientCallbackId`] can be passed to [`Self::remove_on_revoke_privilage_from_client`]
    /// to cancel the callback.
    fn on_revoke_privilage_from_client(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PrivilegedClientIdentity) + Send + 'static,
    ) -> RevokePrivilageFromClientCallbackId;
    /// Cancel a callback previously registered by [`Self::on_revoke_privilage_from_client`],
    /// causing it not to run in the future.
    fn remove_on_revoke_privilage_from_client(&self, callback: RevokePrivilageFromClientCallbackId);
}

impl revoke_privilage_from_client for super::RemoteReducers {
    fn revoke_privilage_from_client(
        &self,
        client_identity: PrivilegedClientIdentity,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "revoke_privilage_from_client",
            RevokePrivilageFromClientArgs { client_identity },
        )
    }
    fn on_revoke_privilage_from_client(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PrivilegedClientIdentity)
            + Send
            + 'static,
    ) -> RevokePrivilageFromClientCallbackId {
        RevokePrivilageFromClientCallbackId(self.imp.on_reducer(
            "revoke_privilage_from_client",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RevokePrivilageFromClient { client_identity },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, client_identity)
            }),
        ))
    }
    fn remove_on_revoke_privilage_from_client(
        &self,
        callback: RevokePrivilageFromClientCallbackId,
    ) {
        self.imp
            .remove_on_reducer("revoke_privilage_from_client", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `revoke_privilage_from_client`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_revoke_privilage_from_client {
    /// Set the call-reducer flags for the reducer `revoke_privilage_from_client` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn revoke_privilage_from_client(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_revoke_privilage_from_client for super::SetReducerFlags {
    fn revoke_privilage_from_client(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("revoke_privilage_from_client", flags);
    }
}
