// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sector_upkeep_timer_type::SectorUpkeepTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SectorUpkeepArgs {
    pub timer: SectorUpkeepTimer,
}

impl From<SectorUpkeepArgs> for super::Reducer {
    fn from(args: SectorUpkeepArgs) -> Self {
        Self::SectorUpkeep { timer: args.timer }
    }
}

impl __sdk::InModule for SectorUpkeepArgs {
    type Module = super::RemoteModule;
}

pub struct SectorUpkeepCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sector_upkeep`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sector_upkeep {
    /// Request that the remote module invoke the reducer `sector_upkeep` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_sector_upkeep`] callbacks.
    fn sector_upkeep(&self, timer: SectorUpkeepTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `sector_upkeep`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SectorUpkeepCallbackId`] can be passed to [`Self::remove_on_sector_upkeep`]
    /// to cancel the callback.
    fn on_sector_upkeep(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &SectorUpkeepTimer) + Send + 'static,
    ) -> SectorUpkeepCallbackId;
    /// Cancel a callback previously registered by [`Self::on_sector_upkeep`],
    /// causing it not to run in the future.
    fn remove_on_sector_upkeep(&self, callback: SectorUpkeepCallbackId);
}

impl sector_upkeep for super::RemoteReducers {
    fn sector_upkeep(&self, timer: SectorUpkeepTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("sector_upkeep", SectorUpkeepArgs { timer })
    }
    fn on_sector_upkeep(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &SectorUpkeepTimer) + Send + 'static,
    ) -> SectorUpkeepCallbackId {
        SectorUpkeepCallbackId(self.imp.on_reducer(
            "sector_upkeep",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SectorUpkeep { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_sector_upkeep(&self, callback: SectorUpkeepCallbackId) {
        self.imp.remove_on_reducer("sector_upkeep", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `sector_upkeep`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_sector_upkeep {
    /// Set the call-reducer flags for the reducer `sector_upkeep` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn sector_upkeep(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_sector_upkeep for super::SetReducerFlags {
    fn sector_upkeep(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("sector_upkeep", flags);
    }
}
