// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sector_type::Sector;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sector`.
///
/// Obtain a handle from the [`SectorTableAccess::sector`] method on [`super::RemoteTables`],
/// like `ctx.db.sector()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector().on_insert(...)`.
pub struct SectorTableHandle<'ctx> {
    imp: __sdk::TableHandle<Sector>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sector`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SectorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SectorTableHandle`], which mediates access to the table `sector`.
    fn sector(&self) -> SectorTableHandle<'_>;
}

impl SectorTableAccess for super::RemoteTables {
    fn sector(&self) -> SectorTableHandle<'_> {
        SectorTableHandle {
            imp: self.imp.get_table::<Sector>("sector"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SectorInsertCallbackId(__sdk::CallbackId);
pub struct SectorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SectorTableHandle<'ctx> {
    type Row = Sector;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Sector> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SectorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorInsertCallbackId {
        SectorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SectorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SectorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorDeleteCallbackId {
        SectorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SectorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Sector>("sector");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct SectorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SectorTableHandle<'ctx> {
    type UpdateCallbackId = SectorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SectorUpdateCallbackId {
        SectorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SectorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Sector>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Sector>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `sector`,
/// which allows point queries on the field of the same name
/// via the [`SectorIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector().id().find(...)`.
pub struct SectorIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Sector, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SectorTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sector`.
    pub fn id(&self) -> SectorIdUnique<'ctx> {
        SectorIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SectorIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Sector> {
        self.imp.find(col_val)
    }
}
