// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sector_chat_message_type::SectorChatMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sector_chat_message`.
///
/// Obtain a handle from the [`SectorChatMessageTableAccess::sector_chat_message`] method on [`super::RemoteTables`],
/// like `ctx.db.sector_chat_message()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector_chat_message().on_insert(...)`.
pub struct SectorChatMessageTableHandle<'ctx> {
    imp: __sdk::TableHandle<SectorChatMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sector_chat_message`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SectorChatMessageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SectorChatMessageTableHandle`], which mediates access to the table `sector_chat_message`.
    fn sector_chat_message(&self) -> SectorChatMessageTableHandle<'_>;
}

impl SectorChatMessageTableAccess for super::RemoteTables {
    fn sector_chat_message(&self) -> SectorChatMessageTableHandle<'_> {
        SectorChatMessageTableHandle {
            imp: self
                .imp
                .get_table::<SectorChatMessage>("sector_chat_message"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SectorChatMessageInsertCallbackId(__sdk::CallbackId);
pub struct SectorChatMessageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SectorChatMessageTableHandle<'ctx> {
    type Row = SectorChatMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SectorChatMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SectorChatMessageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorChatMessageInsertCallbackId {
        SectorChatMessageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SectorChatMessageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SectorChatMessageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorChatMessageDeleteCallbackId {
        SectorChatMessageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SectorChatMessageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SectorChatMessage>("sector_chat_message");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct SectorChatMessageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SectorChatMessageTableHandle<'ctx> {
    type UpdateCallbackId = SectorChatMessageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SectorChatMessageUpdateCallbackId {
        SectorChatMessageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SectorChatMessageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SectorChatMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SectorChatMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `sector_chat_message`,
/// which allows point queries on the field of the same name
/// via the [`SectorChatMessageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector_chat_message().id().find(...)`.
pub struct SectorChatMessageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SectorChatMessage, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SectorChatMessageTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sector_chat_message`.
    pub fn id(&self) -> SectorChatMessageIdUnique<'ctx> {
        SectorChatMessageIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SectorChatMessageIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SectorChatMessage> {
        self.imp.find(col_val)
    }
}
