// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sector_upkeep_timer_type::SectorUpkeepTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sector_upkeep_timer`.
///
/// Obtain a handle from the [`SectorUpkeepTimerTableAccess::sector_upkeep_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.sector_upkeep_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector_upkeep_timer().on_insert(...)`.
pub struct SectorUpkeepTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<SectorUpkeepTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sector_upkeep_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SectorUpkeepTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SectorUpkeepTimerTableHandle`], which mediates access to the table `sector_upkeep_timer`.
    fn sector_upkeep_timer(&self) -> SectorUpkeepTimerTableHandle<'_>;
}

impl SectorUpkeepTimerTableAccess for super::RemoteTables {
    fn sector_upkeep_timer(&self) -> SectorUpkeepTimerTableHandle<'_> {
        SectorUpkeepTimerTableHandle {
            imp: self
                .imp
                .get_table::<SectorUpkeepTimer>("sector_upkeep_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SectorUpkeepTimerInsertCallbackId(__sdk::CallbackId);
pub struct SectorUpkeepTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SectorUpkeepTimerTableHandle<'ctx> {
    type Row = SectorUpkeepTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SectorUpkeepTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SectorUpkeepTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorUpkeepTimerInsertCallbackId {
        SectorUpkeepTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SectorUpkeepTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SectorUpkeepTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorUpkeepTimerDeleteCallbackId {
        SectorUpkeepTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SectorUpkeepTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SectorUpkeepTimer>("sector_upkeep_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct SectorUpkeepTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SectorUpkeepTimerTableHandle<'ctx> {
    type UpdateCallbackId = SectorUpkeepTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SectorUpkeepTimerUpdateCallbackId {
        SectorUpkeepTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SectorUpkeepTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SectorUpkeepTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SectorUpkeepTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `sector_upkeep_timer`,
/// which allows point queries on the field of the same name
/// via the [`SectorUpkeepTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector_upkeep_timer().scheduled_id().find(...)`.
pub struct SectorUpkeepTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SectorUpkeepTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SectorUpkeepTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `sector_upkeep_timer`.
    pub fn scheduled_id(&self) -> SectorUpkeepTimerScheduledIdUnique<'ctx> {
        SectorUpkeepTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SectorUpkeepTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SectorUpkeepTimer> {
        self.imp.find(col_val)
    }
}
