// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendSectorChatArgs {
    pub chat_message: String,
    pub sector_id: u64,
}

impl From<SendSectorChatArgs> for super::Reducer {
    fn from(args: SendSectorChatArgs) -> Self {
        Self::SendSectorChat {
            chat_message: args.chat_message,
            sector_id: args.sector_id,
        }
    }
}

impl __sdk::InModule for SendSectorChatArgs {
    type Module = super::RemoteModule;
}

pub struct SendSectorChatCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_sector_chat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_sector_chat {
    /// Request that the remote module invoke the reducer `send_sector_chat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_send_sector_chat`] callbacks.
    fn send_sector_chat(&self, chat_message: String, sector_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `send_sector_chat`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SendSectorChatCallbackId`] can be passed to [`Self::remove_on_send_sector_chat`]
    /// to cancel the callback.
    fn on_send_sector_chat(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u64) + Send + 'static,
    ) -> SendSectorChatCallbackId;
    /// Cancel a callback previously registered by [`Self::on_send_sector_chat`],
    /// causing it not to run in the future.
    fn remove_on_send_sector_chat(&self, callback: SendSectorChatCallbackId);
}

impl send_sector_chat for super::RemoteReducers {
    fn send_sector_chat(&self, chat_message: String, sector_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "send_sector_chat",
            SendSectorChatArgs {
                chat_message,
                sector_id,
            },
        )
    }
    fn on_send_sector_chat(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u64) + Send + 'static,
    ) -> SendSectorChatCallbackId {
        SendSectorChatCallbackId(self.imp.on_reducer(
            "send_sector_chat",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::SendSectorChat {
                                    chat_message,
                                    sector_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, chat_message, sector_id)
            }),
        ))
    }
    fn remove_on_send_sector_chat(&self, callback: SendSectorChatCallbackId) {
        self.imp.remove_on_reducer("send_sector_chat", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `send_sector_chat`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_send_sector_chat {
    /// Set the call-reducer flags for the reducer `send_sector_chat` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn send_sector_chat(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_send_sector_chat for super::SetReducerFlags {
    fn send_sector_chat(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("send_sector_chat", flags);
    }
}
