// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_object_type::ShipObject;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_object`.
///
/// Obtain a handle from the [`ShipObjectTableAccess::ship_object`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_object()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_object().on_insert(...)`.
pub struct ShipObjectTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipObject>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_object`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipObjectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipObjectTableHandle`], which mediates access to the table `ship_object`.
    fn ship_object(&self) -> ShipObjectTableHandle<'_>;
}

impl ShipObjectTableAccess for super::RemoteTables {
    fn ship_object(&self) -> ShipObjectTableHandle<'_> {
        ShipObjectTableHandle {
            imp: self.imp.get_table::<ShipObject>("ship_object"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipObjectInsertCallbackId(__sdk::CallbackId);
pub struct ShipObjectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipObjectTableHandle<'ctx> {
    type Row = ShipObject;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipObject> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipObjectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipObjectInsertCallbackId {
        ShipObjectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipObjectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipObjectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipObjectDeleteCallbackId {
        ShipObjectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipObjectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipObject>("ship_object");
    _table.add_unique_constraint::<u64>("ship_id", |row| &row.ship_id);
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}
pub struct ShipObjectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipObjectTableHandle<'ctx> {
    type UpdateCallbackId = ShipObjectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipObjectUpdateCallbackId {
        ShipObjectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipObjectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipObject>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipObject>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `ship_id` unique index on the table `ship_object`,
/// which allows point queries on the field of the same name
/// via the [`ShipObjectShipIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_object().ship_id().find(...)`.
pub struct ShipObjectShipIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipObject, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipObjectTableHandle<'ctx> {
    /// Get a handle on the `ship_id` unique index on the table `ship_object`.
    pub fn ship_id(&self) -> ShipObjectShipIdUnique<'ctx> {
        ShipObjectShipIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("ship_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipObjectShipIdUnique<'ctx> {
    /// Find the subscribed row whose `ship_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipObject> {
        self.imp.find(col_val)
    }
}

/// Access to the `sobj_id` unique index on the table `ship_object`,
/// which allows point queries on the field of the same name
/// via the [`ShipObjectSobjIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_object().sobj_id().find(...)`.
pub struct ShipObjectSobjIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipObject, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipObjectTableHandle<'ctx> {
    /// Get a handle on the `sobj_id` unique index on the table `ship_object`.
    pub fn sobj_id(&self) -> ShipObjectSobjIdUnique<'ctx> {
        ShipObjectSobjIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipObjectSobjIdUnique<'ctx> {
    /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipObject> {
        self.imp.find(col_val)
    }
}
