// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_cargo_item_type::ShipCargoItem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_cargo_item`.
///
/// Obtain a handle from the [`ShipCargoItemTableAccess::ship_cargo_item`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_cargo_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_cargo_item().on_insert(...)`.
pub struct ShipCargoItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipCargoItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_cargo_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipCargoItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipCargoItemTableHandle`], which mediates access to the table `ship_cargo_item`.
    fn ship_cargo_item(&self) -> ShipCargoItemTableHandle<'_>;
}

impl ShipCargoItemTableAccess for super::RemoteTables {
    fn ship_cargo_item(&self) -> ShipCargoItemTableHandle<'_> {
        ShipCargoItemTableHandle {
            imp: self.imp.get_table::<ShipCargoItem>("ship_cargo_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipCargoItemInsertCallbackId(__sdk::CallbackId);
pub struct ShipCargoItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipCargoItemTableHandle<'ctx> {
    type Row = ShipCargoItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipCargoItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipCargoItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipCargoItemInsertCallbackId {
        ShipCargoItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipCargoItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipCargoItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipCargoItemDeleteCallbackId {
        ShipCargoItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipCargoItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipCargoItem>("ship_cargo_item");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ShipCargoItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipCargoItemTableHandle<'ctx> {
    type UpdateCallbackId = ShipCargoItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipCargoItemUpdateCallbackId {
        ShipCargoItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipCargoItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipCargoItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipCargoItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ship_cargo_item`,
/// which allows point queries on the field of the same name
/// via the [`ShipCargoItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_cargo_item().id().find(...)`.
pub struct ShipCargoItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipCargoItem, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipCargoItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ship_cargo_item`.
    pub fn id(&self) -> ShipCargoItemIdUnique<'ctx> {
        ShipCargoItemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipCargoItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipCargoItem> {
        self.imp.find(col_val)
    }
}
