// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_class_type::ShipClass;
use super::ship_type_definition_type::ShipTypeDefinition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_type_definition`.
///
/// Obtain a handle from the [`ShipTypeDefinitionTableAccess::ship_type_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_type_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_type_definition().on_insert(...)`.
pub struct ShipTypeDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipTypeDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_type_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipTypeDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipTypeDefinitionTableHandle`], which mediates access to the table `ship_type_definition`.
    fn ship_type_definition(&self) -> ShipTypeDefinitionTableHandle<'_>;
}

impl ShipTypeDefinitionTableAccess for super::RemoteTables {
    fn ship_type_definition(&self) -> ShipTypeDefinitionTableHandle<'_> {
        ShipTypeDefinitionTableHandle {
            imp: self
                .imp
                .get_table::<ShipTypeDefinition>("ship_type_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipTypeDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct ShipTypeDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipTypeDefinitionTableHandle<'ctx> {
    type Row = ShipTypeDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipTypeDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipTypeDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipTypeDefinitionInsertCallbackId {
        ShipTypeDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipTypeDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipTypeDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipTypeDefinitionDeleteCallbackId {
        ShipTypeDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipTypeDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipTypeDefinition>("ship_type_definition");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct ShipTypeDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipTypeDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = ShipTypeDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipTypeDefinitionUpdateCallbackId {
        ShipTypeDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipTypeDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipTypeDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipTypeDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ship_type_definition`,
/// which allows point queries on the field of the same name
/// via the [`ShipTypeDefinitionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_type_definition().id().find(...)`.
pub struct ShipTypeDefinitionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipTypeDefinition, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipTypeDefinitionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ship_type_definition`.
    pub fn id(&self) -> ShipTypeDefinitionIdUnique<'ctx> {
        ShipTypeDefinitionIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipTypeDefinitionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ShipTypeDefinition> {
        self.imp.find(col_val)
    }
}
