// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_energy_and_shield_timer_type::ShipEnergyAndShieldTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_energy_and_shield_timer`.
///
/// Obtain a handle from the [`ShipEnergyAndShieldTimerTableAccess::ship_energy_and_shield_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_energy_and_shield_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_energy_and_shield_timer().on_insert(...)`.
pub struct ShipEnergyAndShieldTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipEnergyAndShieldTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_energy_and_shield_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipEnergyAndShieldTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipEnergyAndShieldTimerTableHandle`], which mediates access to the table `ship_energy_and_shield_timer`.
    fn ship_energy_and_shield_timer(&self) -> ShipEnergyAndShieldTimerTableHandle<'_>;
}

impl ShipEnergyAndShieldTimerTableAccess for super::RemoteTables {
    fn ship_energy_and_shield_timer(&self) -> ShipEnergyAndShieldTimerTableHandle<'_> {
        ShipEnergyAndShieldTimerTableHandle {
            imp: self
                .imp
                .get_table::<ShipEnergyAndShieldTimer>("ship_energy_and_shield_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipEnergyAndShieldTimerInsertCallbackId(__sdk::CallbackId);
pub struct ShipEnergyAndShieldTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipEnergyAndShieldTimerTableHandle<'ctx> {
    type Row = ShipEnergyAndShieldTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipEnergyAndShieldTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipEnergyAndShieldTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipEnergyAndShieldTimerInsertCallbackId {
        ShipEnergyAndShieldTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipEnergyAndShieldTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipEnergyAndShieldTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipEnergyAndShieldTimerDeleteCallbackId {
        ShipEnergyAndShieldTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipEnergyAndShieldTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<ShipEnergyAndShieldTimer>("ship_energy_and_shield_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct ShipEnergyAndShieldTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipEnergyAndShieldTimerTableHandle<'ctx> {
    type UpdateCallbackId = ShipEnergyAndShieldTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipEnergyAndShieldTimerUpdateCallbackId {
        ShipEnergyAndShieldTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipEnergyAndShieldTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipEnergyAndShieldTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipEnergyAndShieldTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `ship_energy_and_shield_timer`,
/// which allows point queries on the field of the same name
/// via the [`ShipEnergyAndShieldTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_energy_and_shield_timer().scheduled_id().find(...)`.
pub struct ShipEnergyAndShieldTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipEnergyAndShieldTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipEnergyAndShieldTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `ship_energy_and_shield_timer`.
    pub fn scheduled_id(&self) -> ShipEnergyAndShieldTimerScheduledIdUnique<'ctx> {
        ShipEnergyAndShieldTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipEnergyAndShieldTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipEnergyAndShieldTimer> {
        self.imp.find(col_val)
    }
}
