// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ship_add_cargo_timer_type::ShipAddCargoTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ShipAddCargoTimerReducerArgs {
    pub timer: ShipAddCargoTimer,
}

impl From<ShipAddCargoTimerReducerArgs> for super::Reducer {
    fn from(args: ShipAddCargoTimerReducerArgs) -> Self {
        Self::ShipAddCargoTimerReducer { timer: args.timer }
    }
}

impl __sdk::InModule for ShipAddCargoTimerReducerArgs {
    type Module = super::RemoteModule;
}

pub struct ShipAddCargoTimerReducerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ship_add_cargo_timer_reducer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ship_add_cargo_timer_reducer {
    /// Request that the remote module invoke the reducer `ship_add_cargo_timer_reducer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_ship_add_cargo_timer_reducer`] callbacks.
    fn ship_add_cargo_timer_reducer(&self, timer: ShipAddCargoTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `ship_add_cargo_timer_reducer`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ShipAddCargoTimerReducerCallbackId`] can be passed to [`Self::remove_on_ship_add_cargo_timer_reducer`]
    /// to cancel the callback.
    fn on_ship_add_cargo_timer_reducer(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &ShipAddCargoTimer) + Send + 'static,
    ) -> ShipAddCargoTimerReducerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_ship_add_cargo_timer_reducer`],
    /// causing it not to run in the future.
    fn remove_on_ship_add_cargo_timer_reducer(&self, callback: ShipAddCargoTimerReducerCallbackId);
}

impl ship_add_cargo_timer_reducer for super::RemoteReducers {
    fn ship_add_cargo_timer_reducer(&self, timer: ShipAddCargoTimer) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "ship_add_cargo_timer_reducer",
            ShipAddCargoTimerReducerArgs { timer },
        )
    }
    fn on_ship_add_cargo_timer_reducer(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &ShipAddCargoTimer) + Send + 'static,
    ) -> ShipAddCargoTimerReducerCallbackId {
        ShipAddCargoTimerReducerCallbackId(self.imp.on_reducer(
            "ship_add_cargo_timer_reducer",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ShipAddCargoTimerReducer { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_ship_add_cargo_timer_reducer(&self, callback: ShipAddCargoTimerReducerCallbackId) {
        self.imp
            .remove_on_reducer("ship_add_cargo_timer_reducer", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `ship_add_cargo_timer_reducer`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_ship_add_cargo_timer_reducer {
    /// Set the call-reducer flags for the reducer `ship_add_cargo_timer_reducer` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn ship_add_cargo_timer_reducer(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_ship_add_cargo_timer_reducer for super::SetReducerFlags {
    fn ship_add_cargo_timer_reducer(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("ship_add_cargo_timer_reducer", flags);
    }
}
