// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_add_cargo_timer_type::ShipAddCargoTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_add_cargo_timer`.
///
/// Obtain a handle from the [`ShipAddCargoTimerTableAccess::ship_add_cargo_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_add_cargo_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_add_cargo_timer().on_insert(...)`.
pub struct ShipAddCargoTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipAddCargoTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_add_cargo_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipAddCargoTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipAddCargoTimerTableHandle`], which mediates access to the table `ship_add_cargo_timer`.
    fn ship_add_cargo_timer(&self) -> ShipAddCargoTimerTableHandle<'_>;
}

impl ShipAddCargoTimerTableAccess for super::RemoteTables {
    fn ship_add_cargo_timer(&self) -> ShipAddCargoTimerTableHandle<'_> {
        ShipAddCargoTimerTableHandle {
            imp: self
                .imp
                .get_table::<ShipAddCargoTimer>("ship_add_cargo_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipAddCargoTimerInsertCallbackId(__sdk::CallbackId);
pub struct ShipAddCargoTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipAddCargoTimerTableHandle<'ctx> {
    type Row = ShipAddCargoTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipAddCargoTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipAddCargoTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipAddCargoTimerInsertCallbackId {
        ShipAddCargoTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipAddCargoTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipAddCargoTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipAddCargoTimerDeleteCallbackId {
        ShipAddCargoTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipAddCargoTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipAddCargoTimer>("ship_add_cargo_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct ShipAddCargoTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipAddCargoTimerTableHandle<'ctx> {
    type UpdateCallbackId = ShipAddCargoTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipAddCargoTimerUpdateCallbackId {
        ShipAddCargoTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipAddCargoTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipAddCargoTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipAddCargoTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `ship_add_cargo_timer`,
/// which allows point queries on the field of the same name
/// via the [`ShipAddCargoTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_add_cargo_timer().scheduled_id().find(...)`.
pub struct ShipAddCargoTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipAddCargoTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipAddCargoTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `ship_add_cargo_timer`.
    pub fn scheduled_id(&self) -> ShipAddCargoTimerScheduledIdUnique<'ctx> {
        ShipAddCargoTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipAddCargoTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipAddCargoTimer> {
        self.imp.find(col_val)
    }
}
