// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::current_action_type::CurrentAction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipInstance {
    pub id: u64,
    pub shiptype_id: u32,
    pub owner_id: Option<__sdk::Identity>,
    pub faction_id: Option<u32>,
    pub sobj_id: Option<u64>,
    pub current_sector_id: u64,
    pub health: f32,
    pub shields: f32,
    pub energy: f32,
    pub used_cargo_capacity: u16,
    pub max_cargo_capacity: u16,
    pub ai_state: Option<CurrentAction>,
    pub docked_at_station_id: Option<u64>,
    pub last_update_ts: __sdk::Timestamp,
}

impl __sdk::InModule for ShipInstance {
    type Module = super::RemoteModule;
}
