// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_mining_timer_type::ShipMiningTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_mining_timer`.
///
/// Obtain a handle from the [`ShipMiningTimerTableAccess::ship_mining_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_mining_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_mining_timer().on_insert(...)`.
pub struct ShipMiningTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipMiningTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_mining_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipMiningTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipMiningTimerTableHandle`], which mediates access to the table `ship_mining_timer`.
    fn ship_mining_timer(&self) -> ShipMiningTimerTableHandle<'_>;
}

impl ShipMiningTimerTableAccess for super::RemoteTables {
    fn ship_mining_timer(&self) -> ShipMiningTimerTableHandle<'_> {
        ShipMiningTimerTableHandle {
            imp: self.imp.get_table::<ShipMiningTimer>("ship_mining_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipMiningTimerInsertCallbackId(__sdk::CallbackId);
pub struct ShipMiningTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipMiningTimerTableHandle<'ctx> {
    type Row = ShipMiningTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipMiningTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipMiningTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipMiningTimerInsertCallbackId {
        ShipMiningTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipMiningTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipMiningTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipMiningTimerDeleteCallbackId {
        ShipMiningTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipMiningTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipMiningTimer>("ship_mining_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct ShipMiningTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipMiningTimerTableHandle<'ctx> {
    type UpdateCallbackId = ShipMiningTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipMiningTimerUpdateCallbackId {
        ShipMiningTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipMiningTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipMiningTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipMiningTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `ship_mining_timer`,
/// which allows point queries on the field of the same name
/// via the [`ShipMiningTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_mining_timer().scheduled_id().find(...)`.
pub struct ShipMiningTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipMiningTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipMiningTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `ship_mining_timer`.
    pub fn scheduled_id(&self) -> ShipMiningTimerScheduledIdUnique<'ctx> {
        ShipMiningTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipMiningTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipMiningTimer> {
        self.imp.find(col_val)
    }
}
