// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ship_class_type::ShipClass;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipTypeDefinition {
    pub id: u32,
    pub name: String,
    pub description: Option<String>,
    pub class: ShipClass,
    pub max_health: u16,
    pub max_shield: u16,
    pub max_energy: u16,
    pub base_speed: f32,
    pub base_acceleration: f32,
    pub base_turn_rate: f32,
    pub cargo_capacity: u16,
    pub num_weapon_slots: u8,
    pub num_shield_slots: u8,
    pub num_engine_slots: u8,
    pub num_mining_laser_slots: u8,
    pub num_special_slots: u8,
    pub gfx_key: Option<String>,
}

impl __sdk::InModule for ShipTypeDefinition {
    type Module = super::RemoteModule;
}
