// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stellar_object_transform_internal_type::StellarObjectTransformInternal;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sobj_internal_transform`.
///
/// Obtain a handle from the [`SobjInternalTransformTableAccess::sobj_internal_transform`] method on [`super::RemoteTables`],
/// like `ctx.db.sobj_internal_transform()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_internal_transform().on_insert(...)`.
pub struct SobjInternalTransformTableHandle<'ctx> {
    imp: __sdk::TableHandle<StellarObjectTransformInternal>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sobj_internal_transform`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SobjInternalTransformTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SobjInternalTransformTableHandle`], which mediates access to the table `sobj_internal_transform`.
    fn sobj_internal_transform(&self) -> SobjInternalTransformTableHandle<'_>;
}

impl SobjInternalTransformTableAccess for super::RemoteTables {
    fn sobj_internal_transform(&self) -> SobjInternalTransformTableHandle<'_> {
        SobjInternalTransformTableHandle {
            imp: self
                .imp
                .get_table::<StellarObjectTransformInternal>("sobj_internal_transform"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SobjInternalTransformInsertCallbackId(__sdk::CallbackId);
pub struct SobjInternalTransformDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SobjInternalTransformTableHandle<'ctx> {
    type Row = StellarObjectTransformInternal;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StellarObjectTransformInternal> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SobjInternalTransformInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjInternalTransformInsertCallbackId {
        SobjInternalTransformInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SobjInternalTransformInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SobjInternalTransformDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjInternalTransformDeleteCallbackId {
        SobjInternalTransformDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SobjInternalTransformDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<StellarObjectTransformInternal>("sobj_internal_transform");
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}
pub struct SobjInternalTransformUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SobjInternalTransformTableHandle<'ctx> {
    type UpdateCallbackId = SobjInternalTransformUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SobjInternalTransformUpdateCallbackId {
        SobjInternalTransformUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SobjInternalTransformUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StellarObjectTransformInternal>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<StellarObjectTransformInternal>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

/// Access to the `sobj_id` unique index on the table `sobj_internal_transform`,
/// which allows point queries on the field of the same name
/// via the [`SobjInternalTransformSobjIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_internal_transform().sobj_id().find(...)`.
pub struct SobjInternalTransformSobjIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StellarObjectTransformInternal, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SobjInternalTransformTableHandle<'ctx> {
    /// Get a handle on the `sobj_id` unique index on the table `sobj_internal_transform`.
    pub fn sobj_id(&self) -> SobjInternalTransformSobjIdUnique<'ctx> {
        SobjInternalTransformSobjIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SobjInternalTransformSobjIdUnique<'ctx> {
    /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StellarObjectTransformInternal> {
        self.imp.find(col_val)
    }
}
