// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stellar_object_transform_low_res_type::StellarObjectTransformLowRes;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sobj_low_res_transform`.
///
/// Obtain a handle from the [`SobjLowResTransformTableAccess::sobj_low_res_transform`] method on [`super::RemoteTables`],
/// like `ctx.db.sobj_low_res_transform()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_low_res_transform().on_insert(...)`.
pub struct SobjLowResTransformTableHandle<'ctx> {
    imp: __sdk::TableHandle<StellarObjectTransformLowRes>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sobj_low_res_transform`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SobjLowResTransformTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SobjLowResTransformTableHandle`], which mediates access to the table `sobj_low_res_transform`.
    fn sobj_low_res_transform(&self) -> SobjLowResTransformTableHandle<'_>;
}

impl SobjLowResTransformTableAccess for super::RemoteTables {
    fn sobj_low_res_transform(&self) -> SobjLowResTransformTableHandle<'_> {
        SobjLowResTransformTableHandle {
            imp: self
                .imp
                .get_table::<StellarObjectTransformLowRes>("sobj_low_res_transform"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SobjLowResTransformInsertCallbackId(__sdk::CallbackId);
pub struct SobjLowResTransformDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SobjLowResTransformTableHandle<'ctx> {
    type Row = StellarObjectTransformLowRes;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StellarObjectTransformLowRes> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SobjLowResTransformInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjLowResTransformInsertCallbackId {
        SobjLowResTransformInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SobjLowResTransformInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SobjLowResTransformDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjLowResTransformDeleteCallbackId {
        SobjLowResTransformDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SobjLowResTransformDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<StellarObjectTransformLowRes>("sobj_low_res_transform");
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}
pub struct SobjLowResTransformUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SobjLowResTransformTableHandle<'ctx> {
    type UpdateCallbackId = SobjLowResTransformUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SobjLowResTransformUpdateCallbackId {
        SobjLowResTransformUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SobjLowResTransformUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StellarObjectTransformLowRes>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<StellarObjectTransformLowRes>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

/// Access to the `sobj_id` unique index on the table `sobj_low_res_transform`,
/// which allows point queries on the field of the same name
/// via the [`SobjLowResTransformSobjIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_low_res_transform().sobj_id().find(...)`.
pub struct SobjLowResTransformSobjIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StellarObjectTransformLowRes, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SobjLowResTransformTableHandle<'ctx> {
    /// Get a handle on the `sobj_id` unique index on the table `sobj_low_res_transform`.
    pub fn sobj_id(&self) -> SobjLowResTransformSobjIdUnique<'ctx> {
        SobjLowResTransformSobjIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SobjLowResTransformSobjIdUnique<'ctx> {
    /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StellarObjectTransformLowRes> {
        self.imp.find(col_val)
    }
}
