// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transforms_timer_type::TransformsTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sobj_transform_timer`.
///
/// Obtain a handle from the [`SobjTransformTimerTableAccess::sobj_transform_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.sobj_transform_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_transform_timer().on_insert(...)`.
pub struct SobjTransformTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransformsTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sobj_transform_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SobjTransformTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SobjTransformTimerTableHandle`], which mediates access to the table `sobj_transform_timer`.
    fn sobj_transform_timer(&self) -> SobjTransformTimerTableHandle<'_>;
}

impl SobjTransformTimerTableAccess for super::RemoteTables {
    fn sobj_transform_timer(&self) -> SobjTransformTimerTableHandle<'_> {
        SobjTransformTimerTableHandle {
            imp: self
                .imp
                .get_table::<TransformsTimer>("sobj_transform_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SobjTransformTimerInsertCallbackId(__sdk::CallbackId);
pub struct SobjTransformTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SobjTransformTimerTableHandle<'ctx> {
    type Row = TransformsTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransformsTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SobjTransformTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjTransformTimerInsertCallbackId {
        SobjTransformTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SobjTransformTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SobjTransformTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjTransformTimerDeleteCallbackId {
        SobjTransformTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SobjTransformTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransformsTimer>("sobj_transform_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct SobjTransformTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SobjTransformTimerTableHandle<'ctx> {
    type UpdateCallbackId = SobjTransformTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SobjTransformTimerUpdateCallbackId {
        SobjTransformTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SobjTransformTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TransformsTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransformsTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `sobj_transform_timer`,
/// which allows point queries on the field of the same name
/// via the [`SobjTransformTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_transform_timer().scheduled_id().find(...)`.
pub struct SobjTransformTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TransformsTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SobjTransformTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `sobj_transform_timer`.
    pub fn scheduled_id(&self) -> SobjTransformTimerScheduledIdUnique<'ctx> {
        SobjTransformTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SobjTransformTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TransformsTimer> {
        self.imp.find(col_val)
    }
}
