// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stellar_object_velocity_type::StellarObjectVelocity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sobj_velocity`.
///
/// Obtain a handle from the [`SobjVelocityTableAccess::sobj_velocity`] method on [`super::RemoteTables`],
/// like `ctx.db.sobj_velocity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_velocity().on_insert(...)`.
pub struct SobjVelocityTableHandle<'ctx> {
    imp: __sdk::TableHandle<StellarObjectVelocity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sobj_velocity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SobjVelocityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SobjVelocityTableHandle`], which mediates access to the table `sobj_velocity`.
    fn sobj_velocity(&self) -> SobjVelocityTableHandle<'_>;
}

impl SobjVelocityTableAccess for super::RemoteTables {
    fn sobj_velocity(&self) -> SobjVelocityTableHandle<'_> {
        SobjVelocityTableHandle {
            imp: self.imp.get_table::<StellarObjectVelocity>("sobj_velocity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SobjVelocityInsertCallbackId(__sdk::CallbackId);
pub struct SobjVelocityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SobjVelocityTableHandle<'ctx> {
    type Row = StellarObjectVelocity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StellarObjectVelocity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SobjVelocityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjVelocityInsertCallbackId {
        SobjVelocityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SobjVelocityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SobjVelocityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjVelocityDeleteCallbackId {
        SobjVelocityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SobjVelocityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StellarObjectVelocity>("sobj_velocity");
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}
pub struct SobjVelocityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SobjVelocityTableHandle<'ctx> {
    type UpdateCallbackId = SobjVelocityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SobjVelocityUpdateCallbackId {
        SobjVelocityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SobjVelocityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StellarObjectVelocity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StellarObjectVelocity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `sobj_id` unique index on the table `sobj_velocity`,
/// which allows point queries on the field of the same name
/// via the [`SobjVelocitySobjIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_velocity().sobj_id().find(...)`.
pub struct SobjVelocitySobjIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StellarObjectVelocity, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SobjVelocityTableHandle<'ctx> {
    /// Get a handle on the `sobj_id` unique index on the table `sobj_velocity`.
    pub fn sobj_id(&self) -> SobjVelocitySobjIdUnique<'ctx> {
        SobjVelocitySobjIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SobjVelocitySobjIdUnique<'ctx> {
    /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StellarObjectVelocity> {
        self.imp.find(col_val)
    }
}
