// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stellar_object_player_window_type::StellarObjectPlayerWindow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sobj_player_window`.
///
/// Obtain a handle from the [`SobjPlayerWindowTableAccess::sobj_player_window`] method on [`super::RemoteTables`],
/// like `ctx.db.sobj_player_window()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_player_window().on_insert(...)`.
pub struct SobjPlayerWindowTableHandle<'ctx> {
    imp: __sdk::TableHandle<StellarObjectPlayerWindow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sobj_player_window`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SobjPlayerWindowTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SobjPlayerWindowTableHandle`], which mediates access to the table `sobj_player_window`.
    fn sobj_player_window(&self) -> SobjPlayerWindowTableHandle<'_>;
}

impl SobjPlayerWindowTableAccess for super::RemoteTables {
    fn sobj_player_window(&self) -> SobjPlayerWindowTableHandle<'_> {
        SobjPlayerWindowTableHandle {
            imp: self
                .imp
                .get_table::<StellarObjectPlayerWindow>("sobj_player_window"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SobjPlayerWindowInsertCallbackId(__sdk::CallbackId);
pub struct SobjPlayerWindowDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SobjPlayerWindowTableHandle<'ctx> {
    type Row = StellarObjectPlayerWindow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StellarObjectPlayerWindow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SobjPlayerWindowInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjPlayerWindowInsertCallbackId {
        SobjPlayerWindowInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SobjPlayerWindowInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SobjPlayerWindowDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SobjPlayerWindowDeleteCallbackId {
        SobjPlayerWindowDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SobjPlayerWindowDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StellarObjectPlayerWindow>("sobj_player_window");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}
pub struct SobjPlayerWindowUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SobjPlayerWindowTableHandle<'ctx> {
    type UpdateCallbackId = SobjPlayerWindowUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SobjPlayerWindowUpdateCallbackId {
        SobjPlayerWindowUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SobjPlayerWindowUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StellarObjectPlayerWindow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StellarObjectPlayerWindow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `sobj_player_window`,
/// which allows point queries on the field of the same name
/// via the [`SobjPlayerWindowIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_player_window().identity().find(...)`.
pub struct SobjPlayerWindowIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StellarObjectPlayerWindow, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SobjPlayerWindowTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `sobj_player_window`.
    pub fn identity(&self) -> SobjPlayerWindowIdentityUnique<'ctx> {
        SobjPlayerWindowIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SobjPlayerWindowIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<StellarObjectPlayerWindow> {
        self.imp.find(col_val)
    }
}

/// Access to the `sobj_id` unique index on the table `sobj_player_window`,
/// which allows point queries on the field of the same name
/// via the [`SobjPlayerWindowSobjIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sobj_player_window().sobj_id().find(...)`.
pub struct SobjPlayerWindowSobjIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StellarObjectPlayerWindow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SobjPlayerWindowTableHandle<'ctx> {
    /// Get a handle on the `sobj_id` unique index on the table `sobj_player_window`.
    pub fn sobj_id(&self) -> SobjPlayerWindowSobjIdUnique<'ctx> {
        SobjPlayerWindowSobjIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SobjPlayerWindowSobjIdUnique<'ctx> {
    /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StellarObjectPlayerWindow> {
        self.imp.find(col_val)
    }
}
