// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::station_kind_type::StationKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Station {
    pub id: u64,
    pub kind: StationKind,
    pub current_sector_id: u32,
    pub sobj_id: u64,
    pub owner_faction_id: u32,
    pub name: String,
    pub gfx_key: Option<String>,
}

impl __sdk::InModule for Station {
    type Module = super::RemoteModule;
}
