// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StellarObjectPlayerWindow {
    pub identity: __sdk::Identity,
    pub sobj_id: u64,
    pub window: f32,
    pub margin: f32,
    pub tl_x: f32,
    pub tl_y: f32,
    pub br_x: f32,
    pub br_y: f32,
}

impl __sdk::InModule for StellarObjectPlayerWindow {
    type Module = super::RemoteModule;
}
