// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TryServerOnlyArgs {}

impl From<TryServerOnlyArgs> for super::Reducer {
    fn from(args: TryServerOnlyArgs) -> Self {
        Self::TryServerOnly
    }
}

impl __sdk::InModule for TryServerOnlyArgs {
    type Module = super::RemoteModule;
}

pub struct TryServerOnlyCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `try_server_only`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait try_server_only {
    /// Request that the remote module invoke the reducer `try_server_only` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_try_server_only`] callbacks.
    fn try_server_only(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `try_server_only`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`TryServerOnlyCallbackId`] can be passed to [`Self::remove_on_try_server_only`]
    /// to cancel the callback.
    fn on_try_server_only(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> TryServerOnlyCallbackId;
    /// Cancel a callback previously registered by [`Self::on_try_server_only`],
    /// causing it not to run in the future.
    fn remove_on_try_server_only(&self, callback: TryServerOnlyCallbackId);
}

impl try_server_only for super::RemoteReducers {
    fn try_server_only(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("try_server_only", TryServerOnlyArgs {})
    }
    fn on_try_server_only(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> TryServerOnlyCallbackId {
        TryServerOnlyCallbackId(self.imp.on_reducer(
            "try_server_only",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::TryServerOnly {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_try_server_only(&self, callback: TryServerOnlyCallbackId) {
        self.imp.remove_on_reducer("try_server_only", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `try_server_only`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_try_server_only {
    /// Set the call-reducer flags for the reducer `try_server_only` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn try_server_only(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_try_server_only for super::SetReducerFlags {
    fn try_server_only(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("try_server_only", flags);
    }
}
