// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_controller_type::PlayerController;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerControllerArgs {
    pub controller: PlayerController,
}

impl From<UpdatePlayerControllerArgs> for super::Reducer {
    fn from(args: UpdatePlayerControllerArgs) -> Self {
        Self::UpdatePlayerController {
            controller: args.controller,
        }
    }
}

impl __sdk::InModule for UpdatePlayerControllerArgs {
    type Module = super::RemoteModule;
}

pub struct UpdatePlayerControllerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_controller`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_controller {
    /// Request that the remote module invoke the reducer `update_player_controller` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_player_controller`] callbacks.
    fn update_player_controller(&self, controller: PlayerController) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_player_controller`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdatePlayerControllerCallbackId`] can be passed to [`Self::remove_on_update_player_controller`]
    /// to cancel the callback.
    fn on_update_player_controller(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerController) + Send + 'static,
    ) -> UpdatePlayerControllerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_player_controller`],
    /// causing it not to run in the future.
    fn remove_on_update_player_controller(&self, callback: UpdatePlayerControllerCallbackId);
}

impl update_player_controller for super::RemoteReducers {
    fn update_player_controller(&self, controller: PlayerController) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_player_controller",
            UpdatePlayerControllerArgs { controller },
        )
    }
    fn on_update_player_controller(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerController) + Send + 'static,
    ) -> UpdatePlayerControllerCallbackId {
        UpdatePlayerControllerCallbackId(self.imp.on_reducer(
            "update_player_controller",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdatePlayerController { controller },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, controller)
            }),
        ))
    }
    fn remove_on_update_player_controller(&self, callback: UpdatePlayerControllerCallbackId) {
        self.imp
            .remove_on_reducer("update_player_controller", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_player_controller`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_player_controller {
    /// Set the call-reducer flags for the reducer `update_player_controller` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_player_controller(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_player_controller for super::SetReducerFlags {
    fn update_player_controller(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_player_controller", flags);
    }
}
