// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddPersonArgs {
    pub name: String,
}

impl From<AddPersonArgs> for super::Reducer {
    fn from(args: AddPersonArgs) -> Self {
        Self::AddPerson { name: args.name }
    }
}

impl __sdk::InModule for AddPersonArgs {
    type Module = super::RemoteModule;
}

pub struct AddPersonCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_person`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_person {
    /// Request that the remote module invoke the reducer `add_person` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_person`] callbacks.
    fn add_person(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_person`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddPersonCallbackId`] can be passed to [`Self::remove_on_add_person`]
    /// to cancel the callback.
    fn on_add_person(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> AddPersonCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_person`],
    /// causing it not to run in the future.
    fn remove_on_add_person(&self, callback: AddPersonCallbackId);
}

impl add_person for super::RemoteReducers {
    fn add_person(&self, name: String) -> __sdk::Result<()> {
        self.imp.call_reducer("add_person", AddPersonArgs { name })
    }
    fn on_add_person(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> AddPersonCallbackId {
        AddPersonCallbackId(self.imp.on_reducer(
            "add_person",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddPerson { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_add_person(&self, callback: AddPersonCallbackId) {
        self.imp.remove_on_reducer("add_person", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_person`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_person {
    /// Set the call-reducer flags for the reducer `add_person` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_person(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_person for super::SetReducerFlags {
    fn add_person(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_person", flags);
    }
}
