// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::connection_type::Connection;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `connection`.
///
/// Obtain a handle from the [`ConnectionTableAccess::connection`] method on [`super::RemoteTables`],
/// like `ctx.db.connection()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.connection().on_insert(...)`.
pub struct ConnectionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Connection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `connection`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConnectionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConnectionTableHandle`], which mediates access to the table `connection`.
    fn connection(&self) -> ConnectionTableHandle<'_>;
}

impl ConnectionTableAccess for super::RemoteTables {
    fn connection(&self) -> ConnectionTableHandle<'_> {
        ConnectionTableHandle {
            imp: self.imp.get_table::<Connection>("connection"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConnectionInsertCallbackId(__sdk::CallbackId);
pub struct ConnectionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConnectionTableHandle<'ctx> {
    type Row = Connection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Connection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConnectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConnectionInsertCallbackId {
        ConnectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConnectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConnectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConnectionDeleteCallbackId {
        ConnectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConnectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Connection>("connection");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Connection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Connection>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `connection`,
/// which allows point queries on the field of the same name
/// via the [`ConnectionIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.connection().identity().find(...)`.
pub struct ConnectionIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Connection, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConnectionTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `connection`.
    pub fn identity(&self) -> ConnectionIdentityUnique<'ctx> {
        ConnectionIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConnectionIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Connection> {
        self.imp.find(col_val)
    }
}
