// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateStellarObjectRandomArgs {}

impl From<CreateStellarObjectRandomArgs> for super::Reducer {
    fn from(args: CreateStellarObjectRandomArgs) -> Self {
        Self::CreateStellarObjectRandom
    }
}

impl __sdk::InModule for CreateStellarObjectRandomArgs {
    type Module = super::RemoteModule;
}

pub struct CreateStellarObjectRandomCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_stellar_object_random`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_stellar_object_random {
    /// Request that the remote module invoke the reducer `create_stellar_object_random` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_stellar_object_random`] callbacks.
    fn create_stellar_object_random(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_stellar_object_random`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateStellarObjectRandomCallbackId`] can be passed to [`Self::remove_on_create_stellar_object_random`]
    /// to cancel the callback.
    fn on_create_stellar_object_random(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> CreateStellarObjectRandomCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_stellar_object_random`],
    /// causing it not to run in the future.
    fn remove_on_create_stellar_object_random(&self, callback: CreateStellarObjectRandomCallbackId);
}

impl create_stellar_object_random for super::RemoteReducers {
    fn create_stellar_object_random(&self) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_stellar_object_random",
            CreateStellarObjectRandomArgs {},
        )
    }
    fn on_create_stellar_object_random(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> CreateStellarObjectRandomCallbackId {
        CreateStellarObjectRandomCallbackId(self.imp.on_reducer(
            "create_stellar_object_random",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateStellarObjectRandom {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_create_stellar_object_random(
        &self,
        callback: CreateStellarObjectRandomCallbackId,
    ) {
        self.imp
            .remove_on_reducer("create_stellar_object_random", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_stellar_object_random`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_stellar_object_random {
    /// Set the call-reducer flags for the reducer `create_stellar_object_random` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_stellar_object_random(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_stellar_object_random for super::SetReducerFlags {
    fn create_stellar_object_random(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("create_stellar_object_random", flags);
    }
}
