// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod add_person_reducer;
pub mod asteroid_table;
pub mod asteroid_type;
pub mod connection_table;
pub mod connection_type;
pub mod create_stellar_object_random_reducer;
pub mod create_stellar_object_reducer;
pub mod identity_connected_reducer;
pub mod identity_disconnected_reducer;
pub mod map_view_type;
pub mod person_table;
pub mod person_type;
pub mod player_table;
pub mod player_type;
pub mod resource_type_type;
pub mod say_hello_reducer;
pub mod sector_table;
pub mod sector_type;
pub mod server_only_reducer;
pub mod set_map_view_reducer;
pub mod ship_class_type;
pub mod ship_table;
pub mod ship_type;
pub mod stellar_object_hi_res_table;
pub mod stellar_object_internal_table;
pub mod stellar_object_kinds_type;
pub mod stellar_object_low_res_table;
pub mod stellar_object_table;
pub mod stellar_object_transform_type;
pub mod stellar_object_type;
pub mod stellar_position_type;
pub mod stellar_transform_type;
pub mod update_object_transform_reducer;
pub mod update_sobj_transform_timer_table;
pub mod update_sobj_transforms_reducer;
pub mod update_transforms_timer_type;

pub use add_person_reducer::{add_person, set_flags_for_add_person, AddPersonCallbackId};
pub use asteroid_table::*;
pub use asteroid_type::Asteroid;
pub use connection_table::*;
pub use connection_type::Connection;
pub use create_stellar_object_random_reducer::{
    create_stellar_object_random, set_flags_for_create_stellar_object_random,
    CreateStellarObjectRandomCallbackId,
};
pub use create_stellar_object_reducer::{
    create_stellar_object, set_flags_for_create_stellar_object, CreateStellarObjectCallbackId,
};
pub use identity_connected_reducer::{
    identity_connected, set_flags_for_identity_connected, IdentityConnectedCallbackId,
};
pub use identity_disconnected_reducer::{
    identity_disconnected, set_flags_for_identity_disconnected, IdentityDisconnectedCallbackId,
};
pub use map_view_type::MapView;
pub use person_table::*;
pub use person_type::Person;
pub use player_table::*;
pub use player_type::Player;
pub use resource_type_type::ResourceType;
pub use say_hello_reducer::{say_hello, set_flags_for_say_hello, SayHelloCallbackId};
pub use sector_table::*;
pub use sector_type::Sector;
pub use server_only_reducer::{server_only, set_flags_for_server_only, ServerOnlyCallbackId};
pub use set_map_view_reducer::{set_flags_for_set_map_view, set_map_view, SetMapViewCallbackId};
pub use ship_class_type::ShipClass;
pub use ship_table::*;
pub use ship_type::Ship;
pub use stellar_object_hi_res_table::*;
pub use stellar_object_internal_table::*;
pub use stellar_object_kinds_type::StellarObjectKinds;
pub use stellar_object_low_res_table::*;
pub use stellar_object_table::*;
pub use stellar_object_transform_type::StellarObjectTransform;
pub use stellar_object_type::StellarObject;
pub use stellar_position_type::StellarPosition;
pub use stellar_transform_type::StellarTransform;
pub use update_object_transform_reducer::{
    set_flags_for_update_object_transform, update_object_transform, UpdateObjectTransformCallbackId,
};
pub use update_sobj_transform_timer_table::*;
pub use update_sobj_transforms_reducer::{
    set_flags_for_update_sobj_transforms, update_sobj_transforms, UpdateSobjTransformsCallbackId,
};
pub use update_transforms_timer_type::UpdateTransformsTimer;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AddPerson {
        name: String,
    },
    CreateStellarObject {
        kind: StellarObjectKinds,
        sector_id: u64,
        transform: StellarTransform,
    },
    CreateStellarObjectRandom,
    IdentityConnected,
    IdentityDisconnected,
    SayHello,
    ServerOnly,
    SetMapView {
        new_view: MapView,
    },
    UpdateObjectTransform {
        object: StellarObject,
        transform: StellarTransform,
    },
    UpdateSobjTransforms {
        timer: UpdateTransformsTimer,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AddPerson { .. } => "add_person",
            Reducer::CreateStellarObject { .. } => "create_stellar_object",
            Reducer::CreateStellarObjectRandom => "create_stellar_object_random",
            Reducer::IdentityConnected => "identity_connected",
            Reducer::IdentityDisconnected => "identity_disconnected",
            Reducer::SayHello => "say_hello",
            Reducer::ServerOnly => "server_only",
            Reducer::SetMapView { .. } => "set_map_view",
            Reducer::UpdateObjectTransform { .. } => "update_object_transform",
            Reducer::UpdateSobjTransforms { .. } => "update_sobj_transforms",
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "add_person" => Ok(
                __sdk::parse_reducer_args::<add_person_reducer::AddPersonArgs>(
                    "add_person",
                    &value.args,
                )?
                .into(),
            ),
            "create_stellar_object" => Ok(__sdk::parse_reducer_args::<
                create_stellar_object_reducer::CreateStellarObjectArgs,
            >("create_stellar_object", &value.args)?
            .into()),
            "create_stellar_object_random" => {
                Ok(__sdk::parse_reducer_args::<
                    create_stellar_object_random_reducer::CreateStellarObjectRandomArgs,
                >("create_stellar_object_random", &value.args)?
                .into())
            }
            "identity_connected" => Ok(__sdk::parse_reducer_args::<
                identity_connected_reducer::IdentityConnectedArgs,
            >("identity_connected", &value.args)?
            .into()),
            "identity_disconnected" => Ok(__sdk::parse_reducer_args::<
                identity_disconnected_reducer::IdentityDisconnectedArgs,
            >("identity_disconnected", &value.args)?
            .into()),
            "say_hello" => Ok(
                __sdk::parse_reducer_args::<say_hello_reducer::SayHelloArgs>(
                    "say_hello",
                    &value.args,
                )?
                .into(),
            ),
            "server_only" => Ok(
                __sdk::parse_reducer_args::<server_only_reducer::ServerOnlyArgs>(
                    "server_only",
                    &value.args,
                )?
                .into(),
            ),
            "set_map_view" => Ok(
                __sdk::parse_reducer_args::<set_map_view_reducer::SetMapViewArgs>(
                    "set_map_view",
                    &value.args,
                )?
                .into(),
            ),
            "update_object_transform" => Ok(__sdk::parse_reducer_args::<
                update_object_transform_reducer::UpdateObjectTransformArgs,
            >("update_object_transform", &value.args)?
            .into()),
            "update_sobj_transforms" => Ok(__sdk::parse_reducer_args::<
                update_sobj_transforms_reducer::UpdateSobjTransformsArgs,
            >("update_sobj_transforms", &value.args)?
            .into()),
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    asteroid: __sdk::TableUpdate<Asteroid>,
    connection: __sdk::TableUpdate<Connection>,
    person: __sdk::TableUpdate<Person>,
    player: __sdk::TableUpdate<Player>,
    sector: __sdk::TableUpdate<Sector>,
    ship: __sdk::TableUpdate<Ship>,
    stellar_object: __sdk::TableUpdate<StellarObject>,
    stellar_object_hi_res: __sdk::TableUpdate<StellarObjectTransform>,
    stellar_object_internal: __sdk::TableUpdate<StellarObjectTransform>,
    stellar_object_low_res: __sdk::TableUpdate<StellarObjectTransform>,
    update_sobj_transform_timer: __sdk::TableUpdate<UpdateTransformsTimer>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "asteroid" => {
                    db_update.asteroid = asteroid_table::parse_table_update(table_update)?
                }
                "connection" => {
                    db_update.connection = connection_table::parse_table_update(table_update)?
                }
                "person" => db_update.person = person_table::parse_table_update(table_update)?,
                "player" => db_update.player = player_table::parse_table_update(table_update)?,
                "sector" => db_update.sector = sector_table::parse_table_update(table_update)?,
                "ship" => db_update.ship = ship_table::parse_table_update(table_update)?,
                "stellar_object" => {
                    db_update.stellar_object =
                        stellar_object_table::parse_table_update(table_update)?
                }
                "stellar_object_hi_res" => {
                    db_update.stellar_object_hi_res =
                        stellar_object_hi_res_table::parse_table_update(table_update)?
                }
                "stellar_object_internal" => {
                    db_update.stellar_object_internal =
                        stellar_object_internal_table::parse_table_update(table_update)?
                }
                "stellar_object_low_res" => {
                    db_update.stellar_object_low_res =
                        stellar_object_low_res_table::parse_table_update(table_update)?
                }
                "update_sobj_transform_timer" => {
                    db_update.update_sobj_transform_timer =
                        update_sobj_transform_timer_table::parse_table_update(table_update)?
                }

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.asteroid = cache
            .apply_diff_to_table::<Asteroid>("asteroid", &self.asteroid)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.connection = cache.apply_diff_to_table::<Connection>("connection", &self.connection);
        diff.person = cache
            .apply_diff_to_table::<Person>("person", &self.person)
            .with_updates_by_pk(|row| &row.identity);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.id);
        diff.sector = cache
            .apply_diff_to_table::<Sector>("sector", &self.sector)
            .with_updates_by_pk(|row| &row.id);
        diff.ship = cache
            .apply_diff_to_table::<Ship>("ship", &self.ship)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.stellar_object = cache
            .apply_diff_to_table::<StellarObject>("stellar_object", &self.stellar_object)
            .with_updates_by_pk(|row| &row.id);
        diff.stellar_object_hi_res = cache.apply_diff_to_table::<StellarObjectTransform>(
            "stellar_object_hi_res",
            &self.stellar_object_hi_res,
        );
        diff.stellar_object_internal = cache.apply_diff_to_table::<StellarObjectTransform>(
            "stellar_object_internal",
            &self.stellar_object_internal,
        );
        diff.stellar_object_low_res = cache.apply_diff_to_table::<StellarObjectTransform>(
            "stellar_object_low_res",
            &self.stellar_object_low_res,
        );
        diff.update_sobj_transform_timer = cache
            .apply_diff_to_table::<UpdateTransformsTimer>(
                "update_sobj_transform_timer",
                &self.update_sobj_transform_timer,
            )
            .with_updates_by_pk(|row| &row.scheduled_id);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    asteroid: __sdk::TableAppliedDiff<'r, Asteroid>,
    connection: __sdk::TableAppliedDiff<'r, Connection>,
    person: __sdk::TableAppliedDiff<'r, Person>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    sector: __sdk::TableAppliedDiff<'r, Sector>,
    ship: __sdk::TableAppliedDiff<'r, Ship>,
    stellar_object: __sdk::TableAppliedDiff<'r, StellarObject>,
    stellar_object_hi_res: __sdk::TableAppliedDiff<'r, StellarObjectTransform>,
    stellar_object_internal: __sdk::TableAppliedDiff<'r, StellarObjectTransform>,
    stellar_object_low_res: __sdk::TableAppliedDiff<'r, StellarObjectTransform>,
    update_sobj_transform_timer: __sdk::TableAppliedDiff<'r, UpdateTransformsTimer>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Asteroid>("asteroid", &self.asteroid, event);
        callbacks.invoke_table_row_callbacks::<Connection>("connection", &self.connection, event);
        callbacks.invoke_table_row_callbacks::<Person>("person", &self.person, event);
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<Sector>("sector", &self.sector, event);
        callbacks.invoke_table_row_callbacks::<Ship>("ship", &self.ship, event);
        callbacks.invoke_table_row_callbacks::<StellarObject>(
            "stellar_object",
            &self.stellar_object,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StellarObjectTransform>(
            "stellar_object_hi_res",
            &self.stellar_object_hi_res,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StellarObjectTransform>(
            "stellar_object_internal",
            &self.stellar_object_internal,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StellarObjectTransform>(
            "stellar_object_low_res",
            &self.stellar_object_low_res,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UpdateTransformsTimer>(
            "update_sobj_transform_timer",
            &self.update_sobj_transform_timer,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SetReducerFlags = SetReducerFlags,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        asteroid_table::register_table(client_cache);
        connection_table::register_table(client_cache);
        person_table::register_table(client_cache);
        player_table::register_table(client_cache);
        sector_table::register_table(client_cache);
        ship_table::register_table(client_cache);
        stellar_object_table::register_table(client_cache);
        stellar_object_hi_res_table::register_table(client_cache);
        stellar_object_internal_table::register_table(client_cache);
        stellar_object_low_res_table::register_table(client_cache);
        update_sobj_transform_timer_table::register_table(client_cache);
    }
}
