// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::move_ships_timer_type::MoveShipsTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveShipsArgs {
    pub timer: MoveShipsTimer,
}

impl From<MoveShipsArgs> for super::Reducer {
    fn from(args: MoveShipsArgs) -> Self {
        Self::MoveShips { timer: args.timer }
    }
}

impl __sdk::InModule for MoveShipsArgs {
    type Module = super::RemoteModule;
}

pub struct MoveShipsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_ships`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_ships {
    /// Request that the remote module invoke the reducer `move_ships` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_move_ships`] callbacks.
    fn move_ships(&self, timer: MoveShipsTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `move_ships`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MoveShipsCallbackId`] can be passed to [`Self::remove_on_move_ships`]
    /// to cancel the callback.
    fn on_move_ships(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &MoveShipsTimer) + Send + 'static,
    ) -> MoveShipsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_move_ships`],
    /// causing it not to run in the future.
    fn remove_on_move_ships(&self, callback: MoveShipsCallbackId);
}

impl move_ships for super::RemoteReducers {
    fn move_ships(&self, timer: MoveShipsTimer) -> __sdk::Result<()> {
        self.imp.call_reducer("move_ships", MoveShipsArgs { timer })
    }
    fn on_move_ships(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &MoveShipsTimer) + Send + 'static,
    ) -> MoveShipsCallbackId {
        MoveShipsCallbackId(self.imp.on_reducer(
            "move_ships",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MoveShips { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_move_ships(&self, callback: MoveShipsCallbackId) {
        self.imp.remove_on_reducer("move_ships", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `move_ships`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_move_ships {
    /// Set the call-reducer flags for the reducer `move_ships` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn move_ships(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_move_ships for super::SetReducerFlags {
    fn move_ships(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("move_ships", flags);
    }
}
