// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::move_ships_timer_type::MoveShipsTimer;

/// Table handle for the table `move_ships_timer`.
///
/// Obtain a handle from the [`MoveShipsTimerTableAccess::move_ships_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.move_ships_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.move_ships_timer().on_insert(...)`.
pub struct MoveShipsTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<MoveShipsTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `move_ships_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MoveShipsTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MoveShipsTimerTableHandle`], which mediates access to the table `move_ships_timer`.
    fn move_ships_timer(&self) -> MoveShipsTimerTableHandle<'_>;
}

impl MoveShipsTimerTableAccess for super::RemoteTables {
    fn move_ships_timer(&self) -> MoveShipsTimerTableHandle<'_> {
        MoveShipsTimerTableHandle {
            imp: self.imp.get_table::<MoveShipsTimer>("move_ships_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MoveShipsTimerInsertCallbackId(__sdk::CallbackId);
pub struct MoveShipsTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MoveShipsTimerTableHandle<'ctx> {
    type Row = MoveShipsTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = MoveShipsTimer> + '_ { self.imp.iter() }

    type InsertCallbackId = MoveShipsTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MoveShipsTimerInsertCallbackId {
        MoveShipsTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MoveShipsTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MoveShipsTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MoveShipsTimerDeleteCallbackId {
        MoveShipsTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MoveShipsTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<MoveShipsTimer>("move_ships_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct MoveShipsTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MoveShipsTimerTableHandle<'ctx> {
    type UpdateCallbackId = MoveShipsTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MoveShipsTimerUpdateCallbackId {
        MoveShipsTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MoveShipsTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}


#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MoveShipsTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<MoveShipsTimer>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        /// Access to the `scheduled_id` unique index on the table `move_ships_timer`,
        /// which allows point queries on the field of the same name
        /// via the [`MoveShipsTimerScheduledIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.move_ships_timer().scheduled_id().find(...)`.
        pub struct MoveShipsTimerScheduledIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<MoveShipsTimer, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> MoveShipsTimerTableHandle<'ctx> {
            /// Get a handle on the `scheduled_id` unique index on the table `move_ships_timer`.
            pub fn scheduled_id(&self) -> MoveShipsTimerScheduledIdUnique<'ctx> {
                MoveShipsTimerScheduledIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> MoveShipsTimerScheduledIdUnique<'ctx> {
            /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<MoveShipsTimer> {
                self.imp.find(col_val)
            }
        }
        