// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::sector_location_type::SectorLocation;

/// Table handle for the table `sector_location`.
///
/// Obtain a handle from the [`SectorLocationTableAccess::sector_location`] method on [`super::RemoteTables`],
/// like `ctx.db.sector_location()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector_location().on_insert(...)`.
pub struct SectorLocationTableHandle<'ctx> {
    imp: __sdk::TableHandle<SectorLocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sector_location`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SectorLocationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SectorLocationTableHandle`], which mediates access to the table `sector_location`.
    fn sector_location(&self) -> SectorLocationTableHandle<'_>;
}

impl SectorLocationTableAccess for super::RemoteTables {
    fn sector_location(&self) -> SectorLocationTableHandle<'_> {
        SectorLocationTableHandle {
            imp: self.imp.get_table::<SectorLocation>("sector_location"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SectorLocationInsertCallbackId(__sdk::CallbackId);
pub struct SectorLocationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SectorLocationTableHandle<'ctx> {
    type Row = SectorLocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = SectorLocation> + '_ { self.imp.iter() }

    type InsertCallbackId = SectorLocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorLocationInsertCallbackId {
        SectorLocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SectorLocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SectorLocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorLocationDeleteCallbackId {
        SectorLocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SectorLocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<SectorLocation>("sector_location");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct SectorLocationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SectorLocationTableHandle<'ctx> {
    type UpdateCallbackId = SectorLocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SectorLocationUpdateCallbackId {
        SectorLocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SectorLocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}


#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SectorLocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<SectorLocation>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        /// Access to the `id` unique index on the table `sector_location`,
        /// which allows point queries on the field of the same name
        /// via the [`SectorLocationIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.sector_location().id().find(...)`.
        pub struct SectorLocationIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<SectorLocation, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> SectorLocationTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `sector_location`.
            pub fn id(&self) -> SectorLocationIdUnique<'ctx> {
                SectorLocationIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> SectorLocationIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<SectorLocation> {
                self.imp.find(col_val)
            }
        }
        