// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::stellar_object_transform_type::StellarObjectTransform;

/// Table handle for the table `stellar_object_hi_res`.
///
/// Obtain a handle from the [`StellarObjectHiResTableAccess::stellar_object_hi_res`] method on [`super::RemoteTables`],
/// like `ctx.db.stellar_object_hi_res()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stellar_object_hi_res().on_insert(...)`.
pub struct StellarObjectHiResTableHandle<'ctx> {
    imp: __sdk::TableHandle<StellarObjectTransform>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stellar_object_hi_res`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StellarObjectHiResTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StellarObjectHiResTableHandle`], which mediates access to the table `stellar_object_hi_res`.
    fn stellar_object_hi_res(&self) -> StellarObjectHiResTableHandle<'_>;
}

impl StellarObjectHiResTableAccess for super::RemoteTables {
    fn stellar_object_hi_res(&self) -> StellarObjectHiResTableHandle<'_> {
        StellarObjectHiResTableHandle {
            imp: self.imp.get_table::<StellarObjectTransform>("stellar_object_hi_res"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StellarObjectHiResInsertCallbackId(__sdk::CallbackId);
pub struct StellarObjectHiResDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StellarObjectHiResTableHandle<'ctx> {
    type Row = StellarObjectTransform;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = StellarObjectTransform> + '_ { self.imp.iter() }

    type InsertCallbackId = StellarObjectHiResInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StellarObjectHiResInsertCallbackId {
        StellarObjectHiResInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StellarObjectHiResInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StellarObjectHiResDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StellarObjectHiResDeleteCallbackId {
        StellarObjectHiResDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StellarObjectHiResDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<StellarObjectTransform>("stellar_object_hi_res");
    _table.add_unique_constraint::<u64>("sobj_id", |row| &row.sobj_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StellarObjectTransform>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<StellarObjectTransform>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        /// Access to the `sobj_id` unique index on the table `stellar_object_hi_res`,
        /// which allows point queries on the field of the same name
        /// via the [`StellarObjectHiResSobjIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.stellar_object_hi_res().sobj_id().find(...)`.
        pub struct StellarObjectHiResSobjIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<StellarObjectTransform, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> StellarObjectHiResTableHandle<'ctx> {
            /// Get a handle on the `sobj_id` unique index on the table `stellar_object_hi_res`.
            pub fn sobj_id(&self) -> StellarObjectHiResSobjIdUnique<'ctx> {
                StellarObjectHiResSobjIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("sobj_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> StellarObjectHiResSobjIdUnique<'ctx> {
            /// Find the subscribed row whose `sobj_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<StellarObjectTransform> {
                self.imp.find(col_val)
            }
        }
        