// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::stellar_object_type::StellarObject;
use super::stellar_transform_type::StellarTransform;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateObjectTransformArgs {
    pub object: StellarObject,
    pub transform: StellarTransform,
}

impl From<UpdateObjectTransformArgs> for super::Reducer {
    fn from(args: UpdateObjectTransformArgs) -> Self {
        Self::UpdateObjectTransform {
            object: args.object,
            transform: args.transform,
        }
    }
}

impl __sdk::InModule for UpdateObjectTransformArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateObjectTransformCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_object_transform`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_object_transform {
    /// Request that the remote module invoke the reducer `update_object_transform` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_object_transform`] callbacks.
    fn update_object_transform(
        &self,
        object: StellarObject,
        transform: StellarTransform,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_object_transform`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateObjectTransformCallbackId`] can be passed to [`Self::remove_on_update_object_transform`]
    /// to cancel the callback.
    fn on_update_object_transform(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &StellarObject, &StellarTransform)
            + Send
            + 'static,
    ) -> UpdateObjectTransformCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_object_transform`],
    /// causing it not to run in the future.
    fn remove_on_update_object_transform(&self, callback: UpdateObjectTransformCallbackId);
}

impl update_object_transform for super::RemoteReducers {
    fn update_object_transform(
        &self,
        object: StellarObject,
        transform: StellarTransform,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_object_transform",
            UpdateObjectTransformArgs { object, transform },
        )
    }
    fn on_update_object_transform(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &StellarObject, &StellarTransform)
            + Send
            + 'static,
    ) -> UpdateObjectTransformCallbackId {
        UpdateObjectTransformCallbackId(self.imp.on_reducer(
            "update_object_transform",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateObjectTransform { object, transform },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, object, transform)
            }),
        ))
    }
    fn remove_on_update_object_transform(&self, callback: UpdateObjectTransformCallbackId) {
        self.imp
            .remove_on_reducer("update_object_transform", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_object_transform`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_object_transform {
    /// Set the call-reducer flags for the reducer `update_object_transform` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_object_transform(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_object_transform for super::SetReducerFlags {
    fn update_object_transform(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_object_transform", flags);
    }
}
