// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_position_timer_type::UpdatePositionTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSobjTransformsArgs {
    pub arg: UpdatePositionTimer,
}

impl From<UpdateSobjTransformsArgs> for super::Reducer {
    fn from(args: UpdateSobjTransformsArgs) -> Self {
        Self::UpdateSobjTransforms { arg: args.arg }
    }
}

impl __sdk::InModule for UpdateSobjTransformsArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateSobjTransformsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_sobj_transforms`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_sobj_transforms {
    /// Request that the remote module invoke the reducer `update_sobj_transforms` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_sobj_transforms`] callbacks.
    fn update_sobj_transforms(&self, arg: UpdatePositionTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_sobj_transforms`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateSobjTransformsCallbackId`] can be passed to [`Self::remove_on_update_sobj_transforms`]
    /// to cancel the callback.
    fn on_update_sobj_transforms(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &UpdatePositionTimer) + Send + 'static,
    ) -> UpdateSobjTransformsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_sobj_transforms`],
    /// causing it not to run in the future.
    fn remove_on_update_sobj_transforms(&self, callback: UpdateSobjTransformsCallbackId);
}

impl update_sobj_transforms for super::RemoteReducers {
    fn update_sobj_transforms(&self, arg: UpdatePositionTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_sobj_transforms", UpdateSobjTransformsArgs { arg })
    }
    fn on_update_sobj_transforms(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &UpdatePositionTimer) + Send + 'static,
    ) -> UpdateSobjTransformsCallbackId {
        UpdateSobjTransformsCallbackId(self.imp.on_reducer(
            "update_sobj_transforms",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateSobjTransforms { arg },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, arg)
            }),
        ))
    }
    fn remove_on_update_sobj_transforms(&self, callback: UpdateSobjTransformsCallbackId) {
        self.imp
            .remove_on_reducer("update_sobj_transforms", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_sobj_transforms`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_sobj_transforms {
    /// Set the call-reducer flags for the reducer `update_sobj_transforms` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_sobj_transforms(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_sobj_transforms for super::SetReducerFlags {
    fn update_sobj_transforms(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_sobj_transforms", flags);
    }
}
