// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::stellar_object_transform_type::StellarObjectTransform;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateStellarObjectVelocityArgs {
    pub velocity: StellarObjectTransform,
}

impl From<UpdateStellarObjectVelocityArgs> for super::Reducer {
    fn from(args: UpdateStellarObjectVelocityArgs) -> Self {
        Self::UpdateStellarObjectVelocity {
            velocity: args.velocity,
}
}
}

impl __sdk::InModule for UpdateStellarObjectVelocityArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateStellarObjectVelocityCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_stellar_object_velocity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_stellar_object_velocity {
    /// Request that the remote module invoke the reducer `update_stellar_object_velocity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_stellar_object_velocity`] callbacks.
    fn update_stellar_object_velocity(&self, velocity: StellarObjectTransform,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_stellar_object_velocity`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateStellarObjectVelocityCallbackId`] can be passed to [`Self::remove_on_update_stellar_object_velocity`]
    /// to cancel the callback.
    fn on_update_stellar_object_velocity(&self, callback: impl FnMut(&super::ReducerEventContext, &StellarObjectTransform, ) + Send + 'static) -> UpdateStellarObjectVelocityCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_stellar_object_velocity`],
    /// causing it not to run in the future.
    fn remove_on_update_stellar_object_velocity(&self, callback: UpdateStellarObjectVelocityCallbackId);
}

impl update_stellar_object_velocity for super::RemoteReducers {
    fn update_stellar_object_velocity(&self, velocity: StellarObjectTransform,
) -> __sdk::Result<()> {
        self.imp.call_reducer("update_stellar_object_velocity", UpdateStellarObjectVelocityArgs { velocity,  })
    }
    fn on_update_stellar_object_velocity(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &StellarObjectTransform, ) + Send + 'static,
    ) -> UpdateStellarObjectVelocityCallbackId {
        UpdateStellarObjectVelocityCallbackId(self.imp.on_reducer(
            "update_stellar_object_velocity",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::UpdateStellarObjectVelocity {
                            velocity, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, velocity, )
            }),
        ))
    }
    fn remove_on_update_stellar_object_velocity(&self, callback: UpdateStellarObjectVelocityCallbackId) {
        self.imp.remove_on_reducer("update_stellar_object_velocity", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_stellar_object_velocity`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_stellar_object_velocity {
    /// Set the call-reducer flags for the reducer `update_stellar_object_velocity` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_stellar_object_velocity(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_stellar_object_velocity for super::SetReducerFlags {
    fn update_stellar_object_velocity(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_stellar_object_velocity", flags);
    }
}

