// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::update_transforms_timer_type::UpdateTransformsTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `update_sobj_transform_timer`.
///
/// Obtain a handle from the [`UpdateSobjTransformTimerTableAccess::update_sobj_transform_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.update_sobj_transform_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.update_sobj_transform_timer().on_insert(...)`.
pub struct UpdateSobjTransformTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<UpdateTransformsTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `update_sobj_transform_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UpdateSobjTransformTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UpdateSobjTransformTimerTableHandle`], which mediates access to the table `update_sobj_transform_timer`.
    fn update_sobj_transform_timer(&self) -> UpdateSobjTransformTimerTableHandle<'_>;
}

impl UpdateSobjTransformTimerTableAccess for super::RemoteTables {
    fn update_sobj_transform_timer(&self) -> UpdateSobjTransformTimerTableHandle<'_> {
        UpdateSobjTransformTimerTableHandle {
            imp: self
                .imp
                .get_table::<UpdateTransformsTimer>("update_sobj_transform_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UpdateSobjTransformTimerInsertCallbackId(__sdk::CallbackId);
pub struct UpdateSobjTransformTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UpdateSobjTransformTimerTableHandle<'ctx> {
    type Row = UpdateTransformsTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UpdateTransformsTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UpdateSobjTransformTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UpdateSobjTransformTimerInsertCallbackId {
        UpdateSobjTransformTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UpdateSobjTransformTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UpdateSobjTransformTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UpdateSobjTransformTimerDeleteCallbackId {
        UpdateSobjTransformTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UpdateSobjTransformTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<UpdateTransformsTimer>("update_sobj_transform_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct UpdateSobjTransformTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UpdateSobjTransformTimerTableHandle<'ctx> {
    type UpdateCallbackId = UpdateSobjTransformTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UpdateSobjTransformTimerUpdateCallbackId {
        UpdateSobjTransformTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UpdateSobjTransformTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UpdateTransformsTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UpdateTransformsTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `update_sobj_transform_timer`,
/// which allows point queries on the field of the same name
/// via the [`UpdateSobjTransformTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.update_sobj_transform_timer().scheduled_id().find(...)`.
pub struct UpdateSobjTransformTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UpdateTransformsTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UpdateSobjTransformTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `update_sobj_transform_timer`.
    pub fn scheduled_id(&self) -> UpdateSobjTransformTimerScheduledIdUnique<'ctx> {
        UpdateSobjTransformTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UpdateSobjTransformTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UpdateTransformsTimer> {
        self.imp.find(col_val)
    }
}
